// 中央路由表：服务端每个 HTTP 端点一行，是 OpenAPI spec（docs/api/openapi.json）的唯一数据源。
// 纪律：
// 1. 新增/修改路由必须同 PR 改这张表并重新生成 spec（`pnpm api:spec`），
//    漏改会被 tests/api-spec-consistency.test.mjs 的「spec ↔ 源码」对账门禁拦下。
// 2. summary/description 是面向 Apifox 的中文文档，必须非空（门禁强制）。
// 3. schema 一律引用 @kenfutwork/shared 的契约变量，禁止就地重写结构；
//    少数派生 schema（.pick / z.object 包装）内联进条目，生成时按匿名 schema 处理。
// 4. 不入 spec 的注册点：/api/ws（WebSocket，见 docs/api/ws-protocol.md）、
//    static-web 的 SPA catch-all（setNotFoundHandler，非 API）。

import {
  agentRunActivityResponseSchema,
  agentRunLatestResponseSchema,
  agentSubagentListResponseSchema,
  assetSignedUrlResponseSchema,
  brandKitAssetCreateRequestSchema,
  brandKitAssetResponseSchema,
  brandKitAssetUpdateRequestSchema,
  brandKitCreateRequestSchema,
  brandKitDetailResponseSchema,
  brandKitListResponseSchema,
  brandKitUpdateRequestSchema,
  canvasGetResponseSchema,
  canvasSaveRequestSchema,
  canvasSaveResponseSchema,
  chatMessageCreateRequestSchema,
  checkpointDiffResponseSchema,
  checkpointFilesResponseSchema,
  checkpointListQuerySchema,
  checkpointListResponseSchema,
  checkpointPreviewResponseSchema,
  checkpointRestoreFileRequestSchema,
  checkpointRestoreRequestSchema,
  checkpointRestoreResponseSchema,
  codeFilesResponseSchema,
  codeGitBranchCreateRequestSchema,
  codeGitChangesResponseSchema,
  codeGitCheckoutRequestSchema,
  codeGitCommitRequestSchema,
  codeGitDiffResponseSchema,
  codeGitDiffStatResponseSchema,
  codeGitDiscardRequestSchema,
  codeGitDiscardResponseSchema,
  codeGitFileResponseSchema,
  codeGitGraphResponseSchema,
  codeGitStageHunkRequestSchema,
  codeGitStageRequestSchema,
  codeGitStageResponseSchema,
  codeGitStatusResponseSchema,
  codeShellsResponseSchema,
  codeTaskScopeResponseSchema,
  codeTaskScopeUpdateRequestSchema,
  codeTerminalRequestSchema,
  codeTerminalResponseSchema,
  codeUiEventStreamSchema,
  codeUiRpcRequestSchema,
  codeUiRpcResponseSchema,
  codeUiSnapshotResponseSchema,
  codeUiWorkspaceListSchema,
  computerUseMcpErrorResponseSchema,
  computerUseMcpEventStreamSchema,
  computerUseMcpMessageSchema,
  computerUseMcpQuerySchema,
  computerUseSnapshotQuerySchema,
  createImageJobRequestSchema,
  createVideoJobRequestSchema,
  directoryPickerStatusSchema,
  executionModeSchema,
  flowEngineInstallStatusSchema,
  flowHostCredentialsRequestSchema,
  flowHostCredentialsResponseSchema,
  flowHostEngineInfoResponseSchema,
  flowHostEngineStopRequestSchema,
  flowHostEventsRequestSchema,
  flowHostEventsResponseSchema,
  flowHostIdentityRequestSchema,
  flowHostIdentityResponseSchema,
  flowHostIdentityTicketResponseSchema,
  flowHostStatusResponseSchema,
  generateImageRequestSchema,
  generateVideoRequestSchema,
  healthResponseSchema,
  instanceDataLocationPrepareRequestSchema,
  instanceDataLocationPrepareResponseSchema,
  instanceDataLocationResponseSchema,
  instanceDataLocationShutdownResponseSchema,
  instanceResponseSchema,
  instanceSettingsResponseSchema,
  instanceSettingsUpdateRequestSchema,
  instanceSkillListResponseSchema,
  instanceSkillToggleRequestSchema,
  jobListResponseSchema,
  jobResponseSchema,
  localAccessClientCreateRequestSchema,
  localAccessClientCreateResponseSchema,
  localAccessClientListResponseSchema,
  localAccessConnectRequestSchema,
  localAccessConnectResponseSchema,
  localAccessTicketRequestSchema,
  localAccessTicketResponseSchema,
  marketplaceInstallRequestSchema,
  mcpServerCreateRequestSchema,
  mcpServerUpdateRequestSchema,
  messageCreateResponseSchema,
  messageListResponseSchema,
  modelCatalogResponseSchema,
  modelListResponseSchema,
  pickDirectoryResponseSchema,
  pluginExportRequestSchema,
  pluginInspectRequestSchema,
  pluginInspectResponseSchema,
  pluginInstallRequestSchema,
  pluginInstallResponseSchema,
  pluginMarketListResponseSchema,
  pluginToggleRequestSchema,
  pluginToggleResponseSchema,
  projectCreateRequestSchema,
  projectCreateResponseSchema,
  projectListQuerySchema,
  projectListResponseSchema,
  projectUpdateRequestSchema,
  providerInstanceCreateRequestSchema,
  providerInstanceListResponseSchema,
  providerInstanceResponseSchema,
  providerInstanceUpdateRequestSchema,
  providerPresetListResponseSchema,
  providerProbeResultSchema,
  runCancelResponseSchema,
  runCreateRequestSchema,
  runCreateResponseSchema,
  sandboxPluginBundleListResponseSchema,
  sandboxPluginInstallRequestSchema,
  sandboxSkillImportRequestSchema,
  sandboxSkillPackageListResponseSchema,
  sessionCreateResponseSchema,
  sessionListResponseSchema,
  skillCreateRequestSchema,
  skillDetailResponseSchema,
  skillImportRequestSchema,
  skillListResponseSchema,
  skillUpdateRequestSchema,
  uploadResponseSchema,
  usageStatsResponseSchema,
  usageSummaryResponseSchema,
  voiceDiagnoseResponseSchema,
  voiceModelListResponseSchema,
  voiceModelResponseSchema,
  voiceRefineRequestSchema,
  voiceRefineResponseSchema,
  voiceSettingsResponseSchema,
  voiceSettingsUpdateRequestSchema,
  voiceSpeakRequestSchema,
  voiceTranscribeResponseSchema,
} from "@kenfutwork/shared";
import type { ZodType } from "zod";
import { z } from "zod";

/** 本机端点统一校验Cookie/Bearer；health与一次性连接兑换为公共引导入口。 */
export type EndpointAuth = "local" | "public" | "shared-secret";

export interface OpenApiRouteEntry {
  method: "get" | "post" | "put" | "patch" | "delete";
  /** Fastify 原样路径（:param / *），生成时转 OpenAPI {param}。 */
  path: string;
  /** 域标签，封闭清单见 tests/api-spec-consistency.test.mjs 的 CLOSED_TAGS。 */
  tag: string;
  summary: string;
  description: string;
  auth: EndpointAuth;
  successStatus: 200 | 201 | 202 | 204 | 503;
  additionalSuccessStatuses?: Array<200 | 202 | 204>;
  errorResponseSchema?: ZodType;
  requestSchema?: ZodType;
  querySchema?: ZodType;
  responseSchema?: ZodType;
  responseMediaType?: "text/event-stream";
  /** multipart 上传：file 为二进制字段名，fields 为附加表单字段（名 → 说明）。 */
  multipart?: { fileField: string; fields?: Record<string, string> };
  /** 成功响应为二进制时的 MIME 类型。 */
  binaryResponse?: string;
}

export const OPENAPI_ROUTES: OpenApiRouteEntry[] = [
  {
    method: "get",
    path: "/api/agent/runs/latest",
    tag: "runs",
    auth: "local",
    successStatus: 200,
    summary: "查询会话最近一轮运行终态",
    description:
      "按持久会话和当前本地实例隔离，返回原始失败原因；没有可见运行时返回 null。",
    responseSchema: agentRunLatestResponseSchema,
    querySchema: z.object({ sessionId: z.string().min(1) }),
  },
  {
    method: "post",
    path: "/api/flow/host/engine/install",
    tag: "flow",
    auth: "local",
    successStatus: 200,
    summary: "开始托管安装 Flow 引擎栈",
    description:
      "本机授权后启动引擎栈安装；安装已在进行中返回 409，客户端通过状态端点观察结果。",
    responseSchema: flowEngineInstallStatusSchema,
  },
  {
    method: "get",
    path: "/api/flow/host/engine/install/status",
    tag: "flow",
    auth: "local",
    successStatus: 200,
    summary: "查询 Flow 引擎栈安装状态",
    description: "返回安装阶段、日志尾部及失败原因；不触发安装。",
    responseSchema: flowEngineInstallStatusSchema,
  },
  {
    method: "post",
    path: "/api/flow/host/engine/stop",
    tag: "flow",
    auth: "local",
    successStatus: 200,
    summary: "停止或卸载 Flow 引擎栈",
    description:
      "本机授权后执行 docker compose down；deleteData=true 时追加 --volumes 全删容器卷（默认保留数据）。失败原样返回可读原因。",
    requestSchema: flowHostEngineStopRequestSchema,
    responseSchema: flowEngineInstallStatusSchema,
  },
  {
    method: "get",
    path: "/api/voice/models",
    tag: "voice",
    auth: "local",
    successStatus: 200,
    summary: "列出语音模型候选",
    description: "列出内置离线模型及当前实例的 BYOK 候选，包含真实下载状态。",
    responseSchema: voiceModelListResponseSchema,
  },
  {
    method: "post",
    path: "/api/voice/models/:modelId/download",
    tag: "voice",
    auth: "local",
    successStatus: 202,
    summary: "下载内置语音模型",
    description: "校验目录 ID、体积与 SHA-256，返回 202 后由候选目录查询进度。",
    responseSchema: voiceModelResponseSchema,
  },
  {
    method: "delete",
    path: "/api/voice/models/:modelId/download",
    tag: "voice",
    auth: "local",
    successStatus: 200,
    summary: "取消内置语音模型下载",
    description: "取消正在进行的下载并返回当前候选状态。",
    responseSchema: voiceModelResponseSchema,
  },
  {
    method: "delete",
    path: "/api/voice/models/:modelId",
    tag: "voice",
    auth: "local",
    successStatus: 200,
    summary: "删除内置语音模型",
    description: "删除当前实例管理的模型文件并返回候选状态。",
    responseSchema: voiceModelResponseSchema,
  },
  {
    method: "get",
    path: "/api/voice/diagnose",
    tag: "voice",
    auth: "local",
    successStatus: 200,
    summary: "读取语音性能检测报告",
    description: "读取本机上次检测报告；尚未检测时返回 null。",
    responseSchema: voiceDiagnoseResponseSchema,
  },
  {
    method: "post",
    path: "/api/voice/diagnose",
    tag: "voice",
    auth: "local",
    successStatus: 200,
    summary: "检测语音性能",
    description: "检测硬件与听、想、说三段，保存报告；请求中止时取消探针。",
    responseSchema: voiceDiagnoseResponseSchema,
  },
  {
    method: "get",
    path: "/api/voice/settings",
    tag: "voice",
    auth: "local",
    successStatus: 200,
    summary: "读取本地实例语音设置",
    description: "读取当前实例的功能模式、三段模型选择与语音回复开关。",
    responseSchema: voiceSettingsResponseSchema,
  },
  {
    method: "put",
    path: "/api/voice/settings",
    tag: "voice",
    auth: "local",
    successStatus: 200,
    summary: "更新本地实例语音设置",
    description: "仅覆盖请求提供的字段，支持显式清空模型选择，持久化后读回。",
    requestSchema: voiceSettingsUpdateRequestSchema,
    responseSchema: voiceSettingsResponseSchema,
  },
  {
    method: "post",
    path: "/api/voice/transcribe",
    tag: "voice",
    auth: "local",
    successStatus: 200,
    summary: "转写录音为文本",
    description:
      "上传 WAV 音频，最大 8 MiB；使用当前实例选择的内置或 BYOK 听段，空文本表示没有识别到语音。",
    multipart: { fileField: "file" },
    responseSchema: voiceTranscribeResponseSchema,
  },
  {
    method: "post",
    path: "/api/voice/refine",
    tag: "voice",
    auth: "local",
    successStatus: 200,
    summary: "整理口述需求",
    description:
      "使用当前实例选择的想段和可选最近上下文，将转写文本整理为完整需求；未选择模型返回可读错误。",
    requestSchema: voiceRefineRequestSchema,
    responseSchema: voiceRefineResponseSchema,
  },
  {
    method: "post",
    path: "/api/voice/speak",
    tag: "voice",
    auth: "local",
    successStatus: 200,
    summary: "合成语音回复",
    description:
      "使用当前实例选择的说段合成音频字节，实际 MIME 由 Provider 决定；请求中止时取消合成。",
    requestSchema: voiceSpeakRequestSchema,
    binaryResponse: "application/octet-stream",
  },

  {
    method: "get",
    path: "/api/computer-use/snapshots",
    tag: "mcp",
    auth: "local",
    successStatus: 200,
    querySchema: computerUseSnapshotQuerySchema,
    binaryResponse: "image/png",
    summary: "读取当前实例Task持有的桌面截图",
    description:
      "大图保存在原blob服务；每次读取重新校验本机凭据与Task实例归属，已删除Task或不存在的截图返回404。引用不含访问令牌，读取字节受实例processMaxOutputBytes预算约束。",
  },

  {
    method: "post",
    path: "/api/computer-use/mcp",
    tag: "mcp",
    auth: "local",
    summary: "调用活动Code Run的桌面MCP",
    description:
      "标准MCP Streamable HTTP：初始化后沿同一Mcp-Session-Id与Mcp-Protocol-Version调用/取消；会话固定本机连接与真实Run，令牌只在HTTP头。JSON-RPC响应为200 SSE消息流，通知受理为202；Run结束/客户端撤权关闭会话。",
    successStatus: 200,
    additionalSuccessStatuses: [202],
    querySchema: computerUseMcpQuerySchema,
    requestSchema: computerUseMcpMessageSchema,
    responseSchema: computerUseMcpEventStreamSchema,
    responseMediaType: "text/event-stream",
    errorResponseSchema: computerUseMcpErrorResponseSchema,
  },
  {
    method: "get",
    path: "/api/computer-use/mcp",
    tag: "mcp",
    auth: "local",
    summary: "订阅活动桌面MCP会话的消息流",
    description:
      "标准MCP SSE通道；须携带初始化取得的Mcp-Session-Id与Mcp-Protocol-Version，每次重连都重验原本机连接和Run。心跳由computerUseMcpKeepAliveMs治理，撤权/Run结束关闭流。",
    successStatus: 200,
    querySchema: computerUseMcpQuerySchema,
    responseSchema: computerUseMcpEventStreamSchema,
    responseMediaType: "text/event-stream",
    errorResponseSchema: computerUseMcpErrorResponseSchema,
  },
  {
    method: "delete",
    path: "/api/computer-use/mcp",
    tag: "mcp",
    auth: "local",
    summary: "结束当前连接的桌面MCP会话",
    description:
      "按标准MCP协议携带Mcp-Session-Id与Mcp-Protocol-Version关闭原SDK transport，取消该会话在途请求；不结束所属Code Run，不重置每Run动作总额。成功为200空体，原nonce不能再使用。",
    successStatus: 200,
    querySchema: computerUseMcpQuerySchema,
    errorResponseSchema: computerUseMcpErrorResponseSchema,
  },

  {
    method: "get",
    path: "/api/instance",
    tag: "instance",
    auth: "local",
    successStatus: 200,
    responseSchema: instanceResponseSchema,
    summary: "读取本地实例",
    description: "返回稳定实例身份与数据根，不创建账户、成员或订阅。",
  },
  {
    method: "get",
    path: "/api/instance/data-location",
    tag: "instance",
    auth: "local",
    successStatus: 200,
    responseSchema: instanceDataLocationResponseSchema,
    summary: "读取本地数据位置",
    description: "返回当前数据目录与受控迁移能力。",
  },
  {
    method: "post",
    path: "/api/instance/data-location/prepare",
    tag: "instance",
    auth: "local",
    successStatus: 200,
    requestSchema: instanceDataLocationPrepareRequestSchema,
    responseSchema: instanceDataLocationPrepareResponseSchema,
    summary: "准备迁移本地数据目录",
    description:
      "桌面宿主专用：校验目标、停止接收新工作并等待在途工作结束；不停止外部数据库。",
  },
  {
    method: "post",
    path: "/api/instance/data-location/shutdown",
    tag: "instance",
    auth: "local",
    successStatus: 202,
    responseSchema: instanceDataLocationShutdownResponseSchema,
    summary: "关闭已准备迁移的本机服务",
    description:
      "仅桌面启动凭据可调用；响应发送后停止worker、API与本机数据库。",
  },
  {
    method: "post",
    path: "/api/local-access/tickets",
    tag: "local-access",
    auth: "local",
    successStatus: 200,
    requestSchema: localAccessTicketRequestSchema,
    responseSchema: localAccessTicketResponseSchema,
    summary: "签发一次性浏览器连接入口",
    description: "已授权的交互客户端可签发，脚本凭据不得委托；使用后立即失效。",
  },
  {
    method: "post",
    path: "/api/local-access/connect",
    tag: "local-access",
    auth: "public",
    successStatus: 200,
    requestSchema: localAccessConnectRequestSchema,
    responseSchema: localAccessConnectResponseSchema,
    summary: "兑换本机连接票据",
    description:
      "验证一次性票据后设置HttpOnly本机会话cookie，响应不包含会话令牌。",
  },
  {
    method: "get",
    path: "/api/local-access/clients",
    tag: "local-access",
    auth: "local",
    successStatus: 200,
    responseSchema: localAccessClientListResponseSchema,
    summary: "查询已授权本机客户端",
    description: "仅已授权交互客户端可管理；不返回秘密值或令牌哈希。",
  },
  {
    method: "post",
    path: "/api/local-access/clients",
    tag: "local-access",
    auth: "local",
    successStatus: 201,
    requestSchema: localAccessClientCreateRequestSchema,
    responseSchema: localAccessClientCreateResponseSchema,
    summary: "授权外部脚本客户端",
    description: "脚本Bearer令牌仅签发时返回一次，不能用于签发其他凭据。",
  },
  {
    method: "delete",
    path: "/api/local-access/clients/:id",
    tag: "local-access",
    auth: "local",
    successStatus: 204,
    summary: "撤销本机客户端授权",
    description: "浏览器或脚本授权立即失效；桌面启动凭据不由此接口撤销。",
  },

  {
    method: "get",
    path: "/api/code-ui/events",
    tag: "code",
    auth: "local",
    successStatus: 200,
    responseSchema: codeUiEventStreamSchema,
    responseMediaType: "text/event-stream",
    summary: "订阅 Code 原协议宿主通知流",
    description:
      "认证 SSE 连接先发送原 V4 hello；RPC 使用其 connectionId 完成 clientHello 后订阅。每个 data 记录承载 ready 或原 physical wire frame，订阅初始帧在 RPC ACK 后发送，断线释放 owned 订阅。",
  },
  {
    method: "get",
    path: "/api/code-ui/workspaces",
    tag: "code",
    auth: "local",
    successStatus: 200,
    responseSchema: codeUiWorkspaceListSchema,
    summary: "查询 Code 原界面工作目录",
    description:
      "返回当前认证实例的 Code 项目主目录与附加授权目录；Agent、文件、Git 和终端消费同一执行作用域，Code 不创建或依赖画布。",
  },
  {
    method: "get",
    path: "/api/code-ui/sessions/:sessionId",
    tag: "code",
    auth: "local",
    successStatus: 200,
    responseSchema: codeUiSnapshotResponseSchema,
    summary: "读取 Code 主或子会话原协议快照",
    description:
      "校验会话归属后返回固定 ZCode V4 ConversationSnapshot，子会话从同一权威聚合读取独立转录。",
  },
  {
    method: "post",
    path: "/api/code-ui/rpc",
    tag: "code",
    auth: "local",
    successStatus: 200,
    requestSchema: codeUiRpcRequestSchema,
    responseSchema: codeUiRpcResponseSchema,
    summary: "调用 Code 原界面宿主接口",
    description:
      "按已接通的服务与方法白名单调用原 UI 的宿主能力。命令按 clientId 与 commandId 幂等；相同键不同参数冲突，Key仅在授权设置内可查看复制；MCP配置与REST共用实例记录，目录省略env值，授权编辑按记录ID读取；尚未接通的方法明确拒绝。",
  },
  {
    method: "get",
    path: "/api/code-ui/tasks/:taskId/scope",
    tag: "code",
    auth: "local",
    successStatus: 200,
    responseSchema: codeTaskScopeResponseSchema,
    summary: "查询 Code Task 的执行目录授权",
    description:
      "按认证实例和 Task 身份读取固定主目录、附加目录及沙箱授权代际，不返回密钥或审批凭据。",
  },
  {
    method: "patch",
    path: "/api/code-ui/tasks/:taskId/scope",
    tag: "code",
    auth: "local",
    successStatus: 200,
    requestSchema: codeTaskScopeUpdateRequestSchema,
    responseSchema: codeTaskScopeResponseSchema,
    summary: "调整 Code Task 的附加目录与执行授权",
    description:
      "主目录不可更换；收紧授权先拒绝旧操作并终止受影响的执行资源，确认真实退出后才恢复可执行状态；失败保留撤销失败事实。",
  },

  // ---- blobs.ts（本地 blob 读取；仅 KENFUTWORK_BLOB_DRIVER=local 时挂载）----
  {
    method: "get",
    path: "/api/blobs/:bucket/*",
    tag: "blobs",
    auth: "local",
    successStatus: 200,
    binaryResponse: "application/octet-stream",
    summary: "读取本地 blob 对象",
    description:
      "按桶与对象路径返回本地存储文件内容（按扩展名推断 content-type）。先验证本机接入；非公开桶还要求有效 ?exp&sig HMAC 签名否则403；越界路径按 404 处理。",
  },
  // ---- brand-kits.ts（品牌套件）----
  {
    method: "get",
    path: "/api/brand-kits",
    tag: "brand-kits",
    auth: "local",
    successStatus: 200,
    responseSchema: brandKitListResponseSchema,
    summary: "列出品牌套件",
    description: "返回当前本地实例可见的品牌套件清单。",
  },
  {
    method: "post",
    path: "/api/brand-kits",
    tag: "brand-kits",
    auth: "local",
    successStatus: 201,
    requestSchema: brandKitCreateRequestSchema,
    responseSchema: brandKitDetailResponseSchema,
    summary: "创建品牌套件",
    description:
      "按请求体创建新品牌套件，返回套件详情。请求体校验失败返回 400。",
  },
  {
    method: "get",
    path: "/api/brand-kits/:kitId",
    tag: "brand-kits",
    auth: "local",
    successStatus: 200,
    responseSchema: brandKitDetailResponseSchema,
    summary: "查询品牌套件详情",
    description: "按 kitId 返回品牌套件详情（含资产）。",
  },
  {
    method: "patch",
    path: "/api/brand-kits/:kitId",
    tag: "brand-kits",
    auth: "local",
    successStatus: 200,
    requestSchema: brandKitUpdateRequestSchema,
    responseSchema: brandKitDetailResponseSchema,
    summary: "更新品牌套件",
    description: "按 kitId 部分更新品牌套件信息，返回更新后的详情。",
  },
  {
    method: "post",
    path: "/api/brand-kits/:kitId/duplicate",
    tag: "brand-kits",
    auth: "local",
    successStatus: 201,
    responseSchema: brandKitDetailResponseSchema,
    summary: "复制品牌套件",
    description: "复制指定品牌套件生成新套件，返回新套件详情。无请求体。",
  },
  {
    method: "delete",
    path: "/api/brand-kits/:kitId",
    tag: "brand-kits",
    auth: "local",
    successStatus: 204,
    summary: "删除品牌套件",
    description: "删除指定品牌套件及其资产，成功返回 204。",
  },
  {
    method: "post",
    path: "/api/brand-kits/:kitId/assets/upload",
    tag: "brand-kits",
    auth: "local",
    successStatus: 201,
    multipart: {
      fileField: "file",
      fields: { asset_type: "资产类型，logo 或 image" },
    },
    responseSchema: brandKitAssetResponseSchema,
    summary: "上传品牌资产文件",
    description:
      "以 multipart 上传 logo/图片文件到指定套件；表单字段 asset_type 须为 logo 或 image，MIME 限 png/jpeg/webp/gif/svg。",
  },
  {
    method: "post",
    path: "/api/brand-kits/:kitId/assets",
    tag: "brand-kits",
    auth: "local",
    successStatus: 201,
    requestSchema: brandKitAssetCreateRequestSchema,
    responseSchema: brandKitAssetResponseSchema,
    summary: "创建品牌资产",
    description: "按请求体在套件下创建资产记录，返回资产详情。",
  },
  {
    method: "patch",
    path: "/api/brand-kits/:kitId/assets/:assetId",
    tag: "brand-kits",
    auth: "local",
    successStatus: 200,
    requestSchema: brandKitAssetUpdateRequestSchema,
    responseSchema: brandKitAssetResponseSchema,
    summary: "更新品牌资产",
    description: "按 assetId 更新套件内资产信息，返回更新后的资产。",
  },
  {
    method: "delete",
    path: "/api/brand-kits/:kitId/assets/:assetId",
    tag: "brand-kits",
    auth: "local",
    successStatus: 204,
    summary: "删除品牌资产",
    description: "删除套件内指定资产，成功返回 204。",
  },
  // ---- canvases.ts（画布）----
  {
    method: "get",
    path: "/api/canvases/:canvasId",
    tag: "canvases",
    auth: "local",
    successStatus: 200,
    responseSchema: canvasGetResponseSchema,
    summary: "读取画布内容",
    description: "按 canvasId 返回当前本地实例可见画布的内容与元信息。",
  },
  {
    method: "put",
    path: "/api/canvases/:canvasId",
    tag: "canvases",
    auth: "local",
    successStatus: 200,
    requestSchema: canvasSaveRequestSchema,
    responseSchema: canvasSaveResponseSchema,
    summary: "保存画布内容",
    description:
      "整体覆盖保存画布内容并返回确认。内容可含 base64 图片数据，请求体上限 50MB。",
  },
  // ---- chat.ts（会话与消息）----
  {
    method: "get",
    path: "/api/canvases/:canvasId/sessions",
    tag: "chat",
    auth: "local",
    successStatus: 200,
    responseSchema: sessionListResponseSchema,
    summary: "列出画布会话",
    description: "返回指定画布下的聊天会话列表。",
  },
  {
    method: "post",
    path: "/api/canvases/:canvasId/sessions",
    tag: "chat",
    auth: "local",
    successStatus: 201,
    responseSchema: sessionCreateResponseSchema,
    summary: "创建聊天会话",
    description: "在指定画布下新建聊天会话，可选传入 body.title 作为标题。",
  },
  {
    method: "patch",
    path: "/api/sessions/:sessionId",
    tag: "chat",
    auth: "local",
    successStatus: 200,
    summary: "重命名聊天会话",
    description:
      "更新会话标题（仅当 body.title 提供时才更新），返回 { ok: true }。",
  },
  {
    method: "delete",
    path: "/api/sessions/:sessionId",
    tag: "chat",
    auth: "local",
    successStatus: 200,
    summary: "删除聊天会话",
    description: "删除指定会话，返回 { ok: true }。",
  },
  {
    method: "get",
    path: "/api/sessions/:sessionId/messages",
    tag: "chat",
    auth: "local",
    successStatus: 200,
    responseSchema: messageListResponseSchema,
    summary: "列出会话消息",
    description: "返回指定会话的消息列表。",
  },
  {
    method: "post",
    path: "/api/sessions/:sessionId/messages",
    tag: "chat",
    auth: "local",
    successStatus: 201,
    requestSchema: chatMessageCreateRequestSchema,
    responseSchema: messageCreateResponseSchema,
    summary: "追加会话消息",
    description:
      "向会话追加一条消息（可含 base64 画布选区图片），返回新消息。请求体上限 10MB。",
  },
  // ---- checkpoints.ts（代码模式：检查点）----
  {
    method: "get",
    path: "/api/code/checkpoints",
    tag: "code",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({ taskId: z.string().describe("Task ID（必填）") }),
    responseSchema: checkpointListResponseSchema,
    summary: "列出Task 检查点",
    description:
      "按 taskId 返回Task 的检查点时间线（升序）。taskId 为必填查询参数，缺失返回 400。",
  },
  {
    method: "get",
    path: "/api/code/checkpoints/:checkpointId/diff",
    tag: "code",
    auth: "local",
    successStatus: 200,
    querySchema: checkpointListQuerySchema.extend({
      path: z.string().optional(),
      rootDirectory: z.string().optional(),
    }),
    responseSchema: checkpointDiffResponseSchema,
    summary: "查询检查点差异",
    description:
      "返回当前 Task 检查点相对上一检查点的统一 diff；taskId 必填，可用 path/rootDirectory 限定目录内文件。",
  },
  {
    method: "post",
    path: "/api/code/checkpoints/:checkpointId/preview",
    querySchema: checkpointListQuerySchema.extend({
      path: z.string().optional(),
      rootDirectory: z.string().optional(),
    }),
    tag: "code",
    auth: "local",
    successStatus: 200,
    responseSchema: checkpointPreviewResponseSchema,
    summary: "预览恢复影响",
    description:
      "返回 Task 恢复影响及 expectedVersion；taskId 必填，可选 path/rootDirectory。恢复提交必须携带该预览版本。",
  },
  {
    method: "post",
    path: "/api/code/checkpoints/:checkpointId/restore",
    requestSchema: checkpointRestoreRequestSchema,
    tag: "code",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({ taskId: z.string().describe("Task ID（必填）") }),
    responseSchema: checkpointRestoreResponseSchema,
    summary: "回滚到检查点",
    description:
      "凭 expectedVersion 恢复 Task 授权目录；停止该 Task 的执行资源，核对文件版本和跨 Task 写进程屏障后提交。预览过期或文件冲突返回 409。",
  },
  {
    method: "get",
    path: "/api/code/checkpoints/:checkpointId/files",
    querySchema: checkpointListQuerySchema,
    tag: "code",
    auth: "local",
    successStatus: 200,
    responseSchema: checkpointFilesResponseSchema,
    summary: "列出轮次文件变更",
    description: "返回该检查点对应轮次的逐文件变更清单。",
  },
  {
    method: "post",
    path: "/api/code/checkpoints/:checkpointId/restore-file",
    tag: "code",
    auth: "local",
    successStatus: 200,
    requestSchema: checkpointRestoreFileRequestSchema,
    querySchema: z.object({ taskId: z.string().describe("Task ID（必填）") }),
    responseSchema: checkpointRestoreResponseSchema,
    summary: "撤销单文件变更",
    description:
      "将单个文件恢复到检查点状态；taskId 必填，body 需 path/expectedVersion，可用 rootDirectory 指定授权附加目录。过期预览或写入冲突返回 409。",
  },
  // ---- code-git.ts（代码模式：git 与工作目录）----
  {
    method: "get",
    path: "/api/code/git",
    tag: "code",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({ taskId: z.string().describe("Task ID（必填）") }),
    responseSchema: codeGitStatusResponseSchema,
    summary: "查询 git 状态",
    description:
      "按 taskId 返回项目工作目录的 git 状态（分支、暂存、变更等）。taskId 必填，缺失返回 400。",
  },
  {
    method: "post",
    path: "/api/code/git/checkout",
    tag: "code",
    auth: "local",
    successStatus: 200,
    requestSchema: codeGitCheckoutRequestSchema,
    responseSchema: codeGitStatusResponseSchema,
    summary: "切换 git 分支",
    description: "将项目工作目录切换到指定分支，返回最新 git 状态。",
  },
  {
    method: "get",
    path: "/api/code/git/diff-stat",
    tag: "code",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({ taskId: z.string().describe("Task ID（必填）") }),
    responseSchema: codeGitDiffStatResponseSchema,
    summary: "查询变更统计",
    description: "返回工作目录相对 HEAD 的增删行数统计。taskId 必填。",
  },
  {
    method: "get",
    path: "/api/code/git/graph",
    tag: "code",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({
      taskId: z.string().describe("Task ID（必填）"),
      limit: z
        .string()
        .optional()
        .describe("返回条数上限，服务端夹取到 1..200（默认 30）"),
    }),
    responseSchema: codeGitGraphResponseSchema,
    summary: "查询 git 图谱",
    description: "返回提交图谱。taskId 必填；limit 由服务端夹取到 1..200。",
  },
  {
    method: "get",
    path: "/api/code/git/changes",
    tag: "code",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({ taskId: z.string().describe("Task ID（必填）") }),
    responseSchema: codeGitChangesResponseSchema,
    summary: "列出变更文件清单",
    description:
      "逐文件返回变更状态与增删行数，最多 200 个（超出截断并标注）。taskId 必填。",
  },
  {
    method: "get",
    path: "/api/code/git/diff",
    tag: "code",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({
      taskId: z.string().describe("Task ID（必填）"),
      path: z.string().describe("工作目录内文件相对路径（必填）"),
    }),
    responseSchema: codeGitDiffResponseSchema,
    summary: "查询单文件差异",
    description:
      "返回指定工作目录文件的统一 diff。taskId 与 path 均必填，缺失返回 400。",
  },
  {
    method: "get",
    path: "/api/code/file",
    tag: "code",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({
      taskId: z.string().describe("Task ID（必填）"),
      path: z.string().describe("工作目录内文件相对路径（必填）"),
    }),
    responseSchema: codeGitFileResponseSchema,
    summary: "读取工作目录文件",
    description:
      "只读预览工作目录内单个文件：路径必须落在工作目录内、最多前 256KB，二进制文件只回元信息。",
  },
  {
    method: "get",
    path: "/api/code/files",
    tag: "code",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({
      taskId: z.string().describe("Task ID（必填）"),
      path: z.string().optional().describe("目录相对路径（可选，默认根目录）"),
    }),
    responseSchema: codeFilesResponseSchema,
    summary: "列出工作目录文件",
    description:
      "列出工作目录指定层级的文件与子目录（只列一层）。taskId 必填。",
  },
  {
    method: "post",
    path: "/api/code/terminal",
    tag: "code",
    auth: "local",
    successStatus: 200,
    requestSchema: codeTerminalRequestSchema,
    responseSchema: codeTerminalResponseSchema,
    summary: "执行终端命令",
    description:
      "在Task 授权工作目录里执行一条用户命令（固定 cwd、有超时与输出上限），返回执行结果。",
  },
  {
    method: "post",
    path: "/api/code/git/stage",
    tag: "code",
    auth: "local",
    successStatus: 200,
    requestSchema: codeGitStageRequestSchema,
    responseSchema: codeGitStageResponseSchema,
    summary: "暂存或取消暂存文件",
    description: "设置单个文件的暂存状态，返回该文件最新状态。",
  },
  {
    method: "post",
    path: "/api/code/git/stage-hunk",
    tag: "code",
    auth: "local",
    successStatus: 200,
    requestSchema: codeGitStageHunkRequestSchema,
    responseSchema: codeGitStageResponseSchema,
    summary: "暂存或取消暂存块",
    description:
      "按 patch 暂存或反应用单个 diff 块（可选 reverse/target），返回文件暂存状态。",
  },
  {
    method: "post",
    path: "/api/code/git/discard",
    tag: "code",
    auth: "local",
    successStatus: 200,
    requestSchema: codeGitDiscardRequestSchema,
    responseSchema: codeGitDiscardResponseSchema,
    summary: "撤销实例更改",
    description:
      "撤销单文件（payload.path 存在时，可含未跟踪文件）或全部未提交更改。丢内容操作，界面需二次确认。",
  },
  {
    method: "get",
    path: "/api/code/shells",
    tag: "code",
    auth: "local",
    successStatus: 200,
    responseSchema: codeShellsResponseSchema,
    summary: "列出可用 shell",
    description:
      "返回本机可用的 shell 清单与实例默认项，供终端下拉与设置页共用。",
  },
  {
    method: "post",
    path: "/api/code/git/init",
    tag: "code",
    auth: "local",
    successStatus: 200,
    requestSchema: codeGitCheckoutRequestSchema.pick({ taskId: true }),
    responseSchema: codeGitStatusResponseSchema,
    summary: "初始化 git 仓库",
    description: "在非仓库的工作目录上幂等初始化 git 仓库，返回最新状态。",
  },
  {
    method: "post",
    path: "/api/code/git/commit",
    tag: "code",
    auth: "local",
    successStatus: 200,
    requestSchema: codeGitCommitRequestSchema,
    responseSchema: codeGitStatusResponseSchema,
    summary: "提交暂存更改",
    description: "以给定 message 提交暂存内容，返回最新 git 状态。",
  },
  {
    method: "post",
    path: "/api/code/git/push",
    tag: "code",
    auth: "local",
    successStatus: 200,
    requestSchema: codeGitCheckoutRequestSchema.pick({ taskId: true }),
    responseSchema: codeGitStatusResponseSchema,
    summary: "推送提交到远端",
    description: "将当前分支推送到远端仓库，返回最新 git 状态。",
  },
  {
    method: "post",
    path: "/api/code/git/branch",
    tag: "code",
    auth: "local",
    successStatus: 200,
    requestSchema: codeGitBranchCreateRequestSchema,
    responseSchema: codeGitStatusResponseSchema,
    summary: "新建 git 分支",
    description: "以给定名称在项目仓库创建分支，返回最新 git 状态。",
  },
  // ---- code-index.ts（代码模式：索引；响应为裸对象，未过 zod）----
  {
    method: "get",
    path: "/api/code/index",
    tag: "code",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({ taskId: z.string().describe("Task ID（必填）") }),
    summary: "查询索引状态",
    description:
      "返回Task 授权工作目录的索引统计及该实例的两个开关（codeIndexEnabled、codeIndexAutoNewFolder）。taskId 必填。",
  },
  {
    method: "post",
    path: "/api/code/index/rebuild",
    tag: "code",
    auth: "local",
    successStatus: 200,
    summary: "重建代码索引",
    description:
      "重新扫描工作目录并重建索引，返回新统计。body 中 taskId 必填。",
  },
  {
    method: "delete",
    path: "/api/code/index",
    tag: "code",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({ taskId: z.string().describe("Task ID（必填）") }),
    summary: "清空代码索引",
    description:
      "删除该 Task 的索引缓存文件（本机 <cwd>/.kenfutwork/index/ 下的 JSON），返回 { ok: true }。taskId 必填。",
  },
  {
    method: "get",
    path: "/api/code/index/search",
    tag: "code",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({
      taskId: z.string().describe("Task ID（必填）"),
      q: z.string().describe("搜索关键词（必填）"),
    }),
    summary: "搜索代码索引",
    description:
      "在索引内即时搜索并返回命中与构建时间。索引开关未开返回 409 index_disabled，无索引返回 409 index_not_built，索引过大返回 413 index_too_large。",
  },
  // ---- execution-modes.ts（执行模式）----
  {
    method: "get",
    path: "/api/execution-modes",
    tag: "execution-modes",
    auth: "local",
    successStatus: 200,
    summary: "列出执行模式",
    description: "返回六档执行模式词汇表，形如 { modes: [...] }。",
  },
  {
    method: "get",
    path: "/api/execution-modes/:threadId",
    tag: "execution-modes",
    auth: "local",
    successStatus: 200,
    responseSchema: executionModeSchema,
    summary: "查询线程激活模式",
    description: "返回线程当前激活的执行模式；缓存未命中时回读持久化值。",
  },
  {
    method: "put",
    path: "/api/execution-modes/:threadId",
    tag: "execution-modes",
    auth: "local",
    successStatus: 200,
    requestSchema: z.object({
      mode: executionModeSchema.describe("要激活的执行模式"),
    }),
    summary: "切换线程执行模式",
    description:
      "激活并写穿持久化线程执行模式，返回 { mode }。会话不属当前实例返回 404；请求非法返回 400。",
  },
  // ---- flow-host.ts（flow 集成宿主缝；credentials/billing/events 用共享密钥而非用户令牌）----
  {
    method: "get",
    path: "/api/flow/host/status",
    tag: "flow",
    auth: "local",
    successStatus: 200,
    responseSchema: flowHostStatusResponseSchema,
    summary: "查询 flow 宿主启用状态",
    description:
      "返回 flow 宿主能力是否启用，并附未启用原因（缺共享密钥或前端地址配置）。未配置时也返回 200 + enabled=false。",
  },
  {
    method: "get",
    path: "/api/flow/host/engine",
    tag: "flow",
    auth: "local",
    successStatus: 200,
    summary: "探测 flow 引擎承载环境",
    description:
      "只读探测引擎可承载路径（平台 / WSL2 / 本机容器 / 自管地址），不做安装、下载或拉起。",
  },
  {
    method: "get",
    path: "/api/flow/host/engine/info",
    tag: "flow",
    auth: "local",
    successStatus: 200,
    responseSchema: flowHostEngineInfoResponseSchema,
    summary: "查询 flow 引擎信息页数据",
    description:
      "汇总安装状态、环境探测与引擎栈容器运行态（安装态为进程内快照，有运行中容器时按已就绪校正）；身份回调地址按本次请求主机名拼。数据面未装配时 503。",
  },
  {
    method: "post",
    path: "/api/flow/host/credentials",
    tag: "flow",
    auth: "local",
    successStatus: 200,
    requestSchema: flowHostCredentialsRequestSchema,
    responseSchema: flowHostCredentialsResponseSchema,
    summary: "下发 Dify 引擎凭证",
    description:
      "校验共享密钥后，从平台池解析启用的 dify-engine 实例，向 flow 网关下发引擎地址与明文 API Key。未配密钥 503，无可用实例 404，base_url 缺失或非法 409。",
  },
  {
    method: "post",
    path: "/api/flow/host/events",
    tag: "flow",
    auth: "local",
    successStatus: 200,
    requestSchema: flowHostEventsRequestSchema,
    responseSchema: flowHostEventsResponseSchema,
    summary: "接收 flow 运行事件批次",
    description:
      "校验共享密钥后逐条解析事件归属，经 WebSocket 通道投递 flowRun.event；无法归属或契约不过的事件跳过并计数。批次可跨 run / 跨用户。",
  },
  {
    method: "post",
    path: "/api/flow/host/identity-ticket",
    tag: "flow",
    auth: "local",
    successStatus: 200,
    responseSchema: flowHostIdentityTicketResponseSchema,
    summary: "签发一次性宿主身份票据",
    description:
      "本机接入验证后签发短时一次性票据（治理值 localAccessTicketTtlMs）；宿主前端在 ff-embed 握手里把它注入 flow，由 flow 网关带回 /api/flow/host/identity 验签。",
  },
  {
    method: "post",
    path: "/api/flow/host/identity",
    tag: "flow",
    auth: "local",
    successStatus: 200,
    requestSchema: flowHostIdentityRequestSchema,
    responseSchema: flowHostIdentityResponseSchema,
    summary: "验签宿主身份票据",
    description:
      "校验共享密钥后一次性消费票据，换出稳定 subject（本地实例模型下即实例 instanceId）；伪造、过期与重放一律 401，版本不符 400。",
  },
  // ---- fonts.ts（字体；免鉴权）----
  {
    method: "get",
    path: "/api/fonts",
    tag: "fonts",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({
      search: z.string().optional().describe("按字体族名称过滤"),
      category: z.string().optional().describe("按类别过滤"),
    }),
    summary: "检索谷歌字体列表",
    description:
      "代理 Google Fonts API 并做 24 小时内存缓存。未配置上游密钥或上游失败时返回空列表或旧缓存。",
  },
  // ---- generate.ts（同步生成）----
  {
    method: "post",
    path: "/api/agent/generate-image",
    tag: "generate",
    auth: "local",
    successStatus: 200,
    requestSchema: generateImageRequestSchema,
    summary: "同步生成图片并入库",
    description:
      "按套餐做模型/分辨率/并发校验并预扣积分，经 BYOK 实例图像适配器生成，结果下载转存对象存储后返回签名 URL 与资产 id。缺 providerInstanceId 或 model 返回 400；上游失败 502。",
  },
  {
    method: "post",
    path: "/api/agent/generate-video",
    tag: "generate",
    auth: "local",
    successStatus: 202,
    requestSchema: generateVideoRequestSchema,
    summary: "受理视频生成任务",
    description:
      "校验套餐与积分后创建 video_generation 任务并预扣积分，由 worker 异步执行，进度经 GET /api/jobs/{jobId} 轮询。返回 { job_id, status, prompt }。",
  },
  // ---- health.ts（健康检查；免鉴权）----
  {
    method: "get",
    path: "/api/health",
    tag: "health",
    auth: "public",
    successStatus: 200,
    responseSchema: healthResponseSchema,
    summary: "检查服务健康状态",
    description: "健康探针，返回服务名 kenfutwork-server 与版本号。",
  },
  // ---- image-models.ts / video-models.ts / model-catalog.ts / models.ts（模型）----
  {
    method: "get",
    path: "/api/image-models",
    tag: "models",
    auth: "local",
    successStatus: 200,
    summary: "列出可用图像模型",
    description:
      "从登录用户的供应商实例目录筛选具备 image / image-edit 能力的模型，specifier 形如 <instanceId>:<model>。BYOK-only：内置图像模型目录已退役。",
  },
  {
    method: "get",
    path: "/api/proxy-image",
    tag: "image-proxy",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({
      url: z.string().describe("要代理拉取的外部图片 URL"),
    }),
    binaryResponse: "image/*",
    summary: "代理拉取外部图片",
    description:
      "服务端转发白名单域名的外部图片，绕过浏览器 CORS 限制。白名单 = replicate 系列域名 + KENFUTWORK_IMAGE_PROXY_ALLOWED_HOSTS；非法 url 400、域名不允许 403、上游失败透传或 502。",
  },
  // ---- jobs.ts（后台任务）----
  {
    method: "post",
    path: "/api/jobs/image-generation",
    tag: "jobs",
    auth: "local",
    successStatus: 201,
    requestSchema: createImageJobRequestSchema,
    responseSchema: jobResponseSchema,
    summary: "创建图片生成任务",
    description:
      "校验套餐模型访问与并发后创建 image_generation 任务并扣减积分，扣费失败自动取消任务。",
  },
  {
    method: "post",
    path: "/api/jobs/video-generation",
    tag: "jobs",
    auth: "local",
    successStatus: 201,
    requestSchema: createVideoJobRequestSchema,
    responseSchema: jobResponseSchema,
    summary: "创建视频生成任务",
    description:
      "创建 video_generation 任务并预扣积分，支持时长、分辨率、宽高比、参考图/参考视频等参数透传给 worker。",
  },
  {
    method: "get",
    path: "/api/jobs/:jobId",
    tag: "jobs",
    auth: "local",
    successStatus: 200,
    responseSchema: jobResponseSchema,
    summary: "查询单个任务状态",
    description:
      "按 jobId 返回当前本地实例的任务详情，供客户端轮询异步任务进度。不存在返回 404。",
  },
  {
    method: "get",
    path: "/api/jobs",
    tag: "jobs",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({
      status: z.string().optional().describe("按任务状态过滤（可选）"),
      job_type: z.string().optional().describe("按任务类型过滤（可选）"),
    }),
    responseSchema: jobListResponseSchema,
    summary: "列出当前本地实例任务",
    description:
      "返回当前本地实例任务列表，支持 status 与 job_type 两个可选查询参数过滤。",
  },
  {
    method: "post",
    path: "/api/jobs/:jobId/cancel",
    tag: "jobs",
    auth: "local",
    successStatus: 200,
    responseSchema: jobResponseSchema,
    summary: "取消未完成任务",
    description: "取消指定任务并返回取消后的任务状态。",
  },
  // ---- mcp.ts（MCP 服务器；变更类操作需管理员）----
  {
    method: "get",
    path: "/api/mcp/servers",
    tag: "mcp",
    auth: "local",
    successStatus: 200,
    summary: "列出 MCP 服务器状态",
    description:
      "返回已配置 MCP server 的配置键名与运行状态（不含密钥值），形如 { servers }。",
  },
  {
    method: "get",
    path: "/api/mcp/catalog",
    tag: "mcp",
    auth: "local",
    successStatus: 200,
    summary: "获取精选 MCP 目录",
    description: "返回内置精选 MCP server 目录（离线可用），供前端一键添加。",
  },
  {
    method: "get",
    path: "/api/mcp/registry",
    tag: "mcp",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({
      q: z.string().optional().describe("按名称子串检索（默认空）"),
      limit: z.string().optional().describe("返回条数上限（默认 20）"),
    }),
    summary: "检索官方 MCP 注册表",
    description:
      "代理官方 MCP Registry 的 search 检索。上游不可用返回 502 mcp_registry_unavailable。",
  },
  {
    method: "post",
    path: "/api/mcp/servers",
    tag: "mcp",
    auth: "local",
    successStatus: 201,
    requestSchema: mcpServerCreateRequestSchema,
    summary: "新增 MCP 服务器",
    description:
      "创建 MCP server 配置；连接失败不报错（状态里可查原因），同名已存在返回 409。需已授权的本机接入，未授权接入401。",
  },
  {
    method: "patch",
    path: "/api/mcp/servers/:id",
    tag: "mcp",
    auth: "local",
    successStatus: 200,
    requestSchema: mcpServerUpdateRequestSchema,
    summary: "更新 MCP 服务器配置",
    description:
      "部分更新指定 server 的配置或启停，改完自动重连收敛；不存在返回 404。需已授权的本机接入。",
  },
  {
    method: "delete",
    path: "/api/mcp/servers/:id",
    tag: "mcp",
    auth: "local",
    successStatus: 204,
    summary: "删除 MCP 服务器",
    description:
      "删除指定 server 配置并断开其 stdio 子进程连接；不存在返回 404。需已授权的本机接入。",
  },
  {
    method: "post",
    path: "/api/mcp/servers/:id/reconnect",
    tag: "mcp",
    auth: "local",
    successStatus: 200,
    summary: "手动重连 MCP 服务器",
    description:
      "触发指定 server 手动重连并返回最新运行状态；不存在返回 404。需已授权的本机接入。",
  },
  {
    method: "get",
    path: "/api/model-catalog",
    tag: "models",
    auth: "local",
    successStatus: 200,
    responseSchema: modelCatalogResponseSchema,
    summary: "获取动态模型目录",
    description:
      "从登录用户的供应商实例推导完整模型目录（覆盖各能力模型）。目录读取失败统一 500。",
  },
  {
    method: "get",
    path: "/api/models",
    tag: "models",
    auth: "local",
    successStatus: 200,
    responseSchema: modelListResponseSchema,
    summary: "列出对话模型清单",
    description:
      "返回内置 OpenAI/Google 模型（按环境变量密钥存在与否裁剪），携带有效令牌时并入该用户 BYOK 实例的 chat 模型；未登录仅返回内置清单。",
  },
  // ---- permissions.ts（权限档位）----
  {
    method: "get",
    path: "/api/permissions/tier",
    tag: "permissions",
    auth: "local",
    successStatus: 200,
    summary: "查询权限档位设置",
    description:
      "返回权限档位、自动化档位、自定义规则、浏览器控制相关开关及永久放行工具清单。",
  },
  {
    method: "put",
    path: "/api/permissions/tier",
    tag: "permissions",
    auth: "local",
    successStatus: 200,
    summary: "部分更新权限设置",
    description:
      "只更新请求送来的字段（tier/automationTier/rules 及若干布尔开关），先写库成功后再改内存，返回与 GET 相同形状。",
  },
  {
    method: "post",
    path: "/api/permissions/approve",
    tag: "permissions",
    auth: "local",
    successStatus: 204,
    summary: "设置旧线程工具放行记忆",
    description:
      "为旧线程策略设置 thread/forever 放行记忆，成功无响应体；缺 toolName 或未绑定调用的 scope=once 返回 400。Code 逐调用审批经原 V4 resolveInteraction 回执，绑定用户、Task、Run、参数和有效授权代际。",
  },
  // ---- plugins.ts（插件；变更类操作需管理员）----
  {
    method: "get",
    path: "/api/plugins",
    tag: "plugins",
    auth: "local",
    successStatus: 200,
    responseSchema: pluginMarketListResponseSchema,
    summary: "列出本机插件目录与安装状态",
    description:
      "返回真实系统能力、随发行包及本机安装清单；installed与enabled独立，scope表示Code/Design/共享作用域，ui合并清单及运行时贡献且同键运行时优先。停用仍为已安装，未安装或未启用不提供运行面板入口。",
  },
  {
    method: "post",
    path: "/api/plugins/inspect",
    tag: "plugins",
    auth: "local",
    successStatus: 200,
    requestSchema: pluginInspectRequestSchema,
    responseSchema: pluginInspectResponseSchema,
    summary: "预检插件兼容性",
    description:
      "只校验插件来源与兼容性门禁，不落盘不装载；让 UI 在用户点安装前看到门禁结论。来源拉取失败 502。",
  },
  {
    method: "post",
    path: "/api/plugins/install",
    tag: "plugins",
    auth: "local",
    successStatus: 201,
    requestSchema: pluginInstallRequestSchema,
    responseSchema: pluginInstallResponseSchema,
    summary: "安装插件",
    description:
      "拉取并安装第三方插件，安装前过兼容性门禁，未通过返回 422 及完整报告。body 含 builtin 字段时走内置安装分支。需已授权的本机接入。",
  },
  {
    method: "get",
    path: "/api/plugins/sandbox-bundles",
    tag: "plugins",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({ canvasId: z.string().describe("画布 ID（必填）") }),
    responseSchema: sandboxPluginBundleListResponseSchema,
    summary: "列出工作目录插件包",
    description:
      "按 canvasId 解析画布归属的工作目录，列出其中的插件 bundle 候选，供「从工作目录安装」选择。画布无效返回 404。",
  },
  {
    method: "post",
    path: "/api/plugins/sandbox-install",
    tag: "plugins",
    auth: "local",
    successStatus: 201,
    requestSchema: sandboxPluginInstallRequestSchema,
    responseSchema: pluginInstallResponseSchema,
    summary: "从工作目录安装插件",
    description:
      "把工作目录里的 bundle 目录安装到本实例，禁止生命周期脚本；响应形状与 /api/plugins/install 一致。需已授权的本机接入。",
  },
  {
    method: "get",
    path: "/api/plugins/:pluginId/assets/*",
    tag: "plugins",
    auth: "local",
    successStatus: 200,
    summary: "读取插件静态资源",
    description:
      "公开只读地返回插件声明的静态资源（面板 iframe 可直接加载）；仅在插件清单声明 assets 时开放，越界或缺失一律 404。",
  },
  {
    method: "get",
    path: "/api/plugins/:pluginId/*",
    tag: "plugins",
    auth: "local",
    successStatus: 200,
    summary: "派发插件自定义路由（GET）",
    description:
      "把请求派发给插件运行时注册的路由处理器；默认要求登录，插件可显式声明 public 开放。实际状态码由插件返回决定。",
  },
  {
    method: "post",
    path: "/api/plugins/:pluginId/*",
    tag: "plugins",
    auth: "local",
    successStatus: 200,
    summary: "派发插件自定义路由（POST）",
    description:
      "与 GET 同一派发逻辑，处理插件自定义的 POST 路由；body 与 headers 原样转交插件。实际状态码由插件返回决定。",
  },
  {
    method: "post",
    path: "/api/plugins/:id/uninstall",
    tag: "plugins",
    auth: "local",
    successStatus: 200,
    summary: "卸载插件",
    description:
      "按 id 卸载插件；系统插件返回 403，未安装返回 404。响应 { id, installed: false }。需已授权的本机接入。",
  },
  {
    method: "post",
    path: "/api/plugins/:id/toggle",
    tag: "plugins",
    auth: "local",
    successStatus: 200,
    requestSchema: pluginToggleRequestSchema,
    responseSchema: pluginToggleResponseSchema,
    summary: "切换插件启停",
    description:
      "按 id 启用/禁用已安装插件；返回installed=true及真实enabled，停用不删除包，未安装返回404。需已授权的本机接入。",
  },
  {
    method: "post",
    path: "/api/plugins/export",
    tag: "plugins",
    auth: "local",
    successStatus: 200,
    requestSchema: pluginExportRequestSchema,
    summary: "导出插件 bundle 骨架",
    description:
      "按名称与格式生成双声明插件 bundle 骨架，不落盘，由客户端决定保存位置。",
  },
  // ---- projects.ts（项目）----
  {
    method: "get",
    path: "/api/projects/:projectId",
    tag: "projects",
    auth: "local",
    successStatus: 200,
    summary: "查询单个项目",
    description:
      "按 projectId 返回当前本地实例可见的项目详情，形如 { project }。",
  },
  {
    method: "get",
    path: "/api/projects",
    tag: "projects",
    auth: "local",
    successStatus: 200,
    querySchema: projectListQuerySchema,
    responseSchema: projectListResponseSchema,
    summary: "列出项目",
    description:
      "按 kind（design/code/flow）过滤列出当前本地实例可见的项目列表。",
  },
  {
    method: "delete",
    path: "/api/projects/:projectId",
    tag: "projects",
    auth: "local",
    successStatus: 204,
    summary: "归档（软删）项目",
    description: "归档指定项目（非物理删除），成功返回 204 无响应体。",
  },
  {
    method: "post",
    path: "/api/projects",
    tag: "projects",
    auth: "local",
    successStatus: 201,
    requestSchema: projectCreateRequestSchema,
    responseSchema: projectCreateResponseSchema,
    summary: "创建项目",
    description:
      "按请求体创建新项目并返回创建结果。请求体校验失败返回 400 带 issues。",
  },
  {
    method: "patch",
    path: "/api/projects/:projectId",
    tag: "projects",
    auth: "local",
    successStatus: 204,
    requestSchema: projectUpdateRequestSchema,
    summary: "更新项目",
    description:
      "部分更新项目字段，成功返回 204 无响应体。请求体校验失败返回 400 带 issues。",
  },
  {
    method: "put",
    path: "/api/projects/:projectId/thumbnail",
    tag: "projects",
    auth: "local",
    successStatus: 200,
    multipart: { fileField: "file" },
    summary: "上传项目缩略图",
    description:
      "以 multipart 表单上传项目缩略图文件（上限 2MB），缺省 MIME 按 image/webp 处理并保存。",
  },
  // ---- provider-instances.ts（BYOK 供应商实例；apiKey存于本地明文凭据文件，授权设置可读取）----
  {
    method: "get",
    path: "/api/provider-instances",
    tag: "provider-instances",
    auth: "local",
    successStatus: 200,
    responseSchema: providerInstanceListResponseSchema,
    summary: "列出供应商实例",
    description:
      "列出当前本地实例的模型供应商实例；只含 hasCredential 布尔，永不回传 apiKey。",
  },
  {
    method: "post",
    path: "/api/provider-instances",
    tag: "provider-instances",
    auth: "local",
    successStatus: 201,
    requestSchema: providerInstanceCreateRequestSchema,
    responseSchema: providerInstanceResponseSchema,
    summary: "创建供应商实例",
    description:
      "创建供应商实例，apiKey存于本地明文凭据文件，授权设置可读取；非法头名/保留头/CRLF 等校验失败返回 400。",
  },
  {
    method: "patch",
    path: "/api/provider-instances/:instanceId",
    tag: "provider-instances",
    auth: "local",
    successStatus: 200,
    requestSchema: providerInstanceUpdateRequestSchema,
    responseSchema: providerInstanceResponseSchema,
    summary: "更新供应商实例",
    description: "更新供应商实例配置；apiKey 缺省即不改，传入即覆盖。",
  },
  {
    method: "get",
    path: "/api/provider-instances/presets",
    tag: "provider-instances",
    auth: "local",
    successStatus: 200,
    responseSchema: providerPresetListResponseSchema,
    summary: "列出供应商预设",
    description:
      "返回 models.dev 供应商预设（供「从预设选择」）；非权威 UI 数据，capability 由模态推导，用户可改。公开端点。",
  },
  {
    method: "post",
    path: "/api/provider-instances/:instanceId/probe",
    tag: "provider-instances",
    auth: "local",
    successStatus: 200,
    responseSchema: providerProbeResultSchema,
    summary: "探测实例连通能力",
    description:
      "对指定实例做连通性与中转方言四项探测，结果缓存到实例，运行期据此裁剪请求。无请求体。",
  },
  {
    method: "delete",
    path: "/api/provider-instances/:instanceId",
    tag: "provider-instances",
    auth: "local",
    successStatus: 204,
    summary: "删除供应商实例",
    description: "删除指定供应商实例，成功返回 204 无响应体。",
  },
  // ---- runs.ts（智能体运行）----
  {
    method: "get",
    path: "/api/agent/subagents",
    tag: "runs",
    auth: "local",
    successStatus: 200,
    responseSchema: agentSubagentListResponseSchema,
    summary: "列出子智能体清单",
    description:
      "返回子智能体定义注册表清单及内置派发工具（task/task_background），与真实运行同一来源。鉴权未装配时返回 503。",
  },
  {
    method: "get",
    path: "/api/agent/runs/activity",
    tag: "runs",
    auth: "local",
    successStatus: 200,
    responseSchema: agentRunActivityResponseSchema,
    summary: "查询实例运行活动",
    description:
      "返回当前实例近 7 天的运行次数与累计时长；解析不到实例时返回全 0，不区分不存在与无权限。",
  },
  {
    method: "post",
    path: "/api/agent/runs",
    tag: "runs",
    auth: "local",
    successStatus: 202,
    requestSchema: runCreateRequestSchema,
    responseSchema: runCreateResponseSchema,
    summary: "创建智能体运行",
    description:
      "以已授权本机身份启动运行。Code绑定Project与持久Task工作域，Design沿用Canvas；读取本地模型与执行模式，任何存储故障都拒绝启动，维护期间不接收新工作。BYOK不检查套餐或余额，成功202返回runId。",
  },
  {
    method: "post",
    path: "/api/agent/runs/:runId/cancel",
    tag: "runs",
    auth: "local",
    successStatus: 202,
    responseSchema: runCancelResponseSchema,
    summary: "取消运行",
    description:
      "按 runId 取消进行中的运行，找不到返回 404，成功返回 202 与取消结果。",
  },
  // ---- settings.ts（实例设置）----
  {
    method: "get",
    path: "/api/instance/settings",
    tag: "settings",
    auth: "local",
    successStatus: 200,
    responseSchema: instanceSettingsResponseSchema,
    summary: "读取实例设置",
    description:
      "解析当前本地实例后返回其已解析设置；modelDefaults 独立持有聊天引用、图像和视频自动或手动候选，未配置聊天默认可为 null。压缩保留字段表示近期原始消息的配置目标，不表示 SDK 实际保留量。模型流无输出阈值仅计真实模型请求，不含工具执行和人工审批等待；0表示关闭。",
  },
  {
    method: "patch",
    path: "/api/instance/settings",
    tag: "settings",
    auth: "local",
    successStatus: 200,
    requestSchema: instanceSettingsUpdateRequestSchema,
    responseSchema: instanceSettingsResponseSchema,
    summary: "更新实例设置",
    description:
      "仅更新送来的实例设置字段，未配置默认模型也可保存其他设置。modelDefaults 使用规范化的 providerId 与 modelId 精确引用；手动候选非空且不重复，必须属于当前实例可用的对应能力目录，Flow 连接不能作为候选。结构错误返回 400 invalid_request，候选不可用返回 400 invalid_model；数据库写入失败整个 patch 回滚。压缩保留目标按窗口已知/未知分别设置，自动与手动维护共用。模型流无输出阈值由实例设置优先于env解析，仅计真实模型请求，0表示关闭。",
  },
  // ---- skills.ts（技能；含实例安装态）----
  {
    method: "get",
    path: "/api/skills",
    tag: "skills",
    auth: "local",
    successStatus: 200,
    responseSchema: skillListResponseSchema,
    summary: "列出可见技能",
    description: "列出当前本地实例可见的技能目录（内置/社区或本人创建）。",
  },
  {
    method: "get",
    path: "/api/skills/:id",
    tag: "skills",
    auth: "local",
    successStatus: 200,
    responseSchema: skillDetailResponseSchema,
    summary: "查询技能详情",
    description:
      "按 id 返回技能详情（含正文、来源等）及关联文件列表；不可见返回 404。",
  },
  {
    method: "get",
    path: "/api/skills/:id/files",
    tag: "skills",
    auth: "local",
    successStatus: 200,
    summary: "列出技能文件",
    description:
      "按 id 返回技能附带文件的清单（路径、内容、mime 等），形如 { files }。",
  },
  {
    method: "post",
    path: "/api/skills",
    tag: "skills",
    auth: "local",
    successStatus: 201,
    requestSchema: skillCreateRequestSchema,
    responseSchema: skillDetailResponseSchema,
    summary: "创建自定义技能",
    description:
      "创建自定义技能（名称生成 slug），可附带文件；同名冲突返回 409，文件写入失败仅记日志不阻断。",
  },
  {
    method: "post",
    path: "/api/skills/import",
    tag: "skills",
    auth: "local",
    successStatus: 201,
    requestSchema: skillImportRequestSchema,
    responseSchema: skillDetailResponseSchema,
    summary: "从 URL 导入技能",
    description:
      "从外部 URL（GitHub/npm tarball/zip）下载 SKILL.md 与附属文件，落库并自动装进当前实例。同名 409。",
  },
  {
    method: "get",
    path: "/api/skills/sandbox-packages",
    tag: "skills",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({ canvasId: z.string().describe("画布 ID（必填）") }),
    responseSchema: sandboxSkillPackageListResponseSchema,
    summary: "列出工作目录技能包",
    description:
      "按 canvasId 校验归属后扫描工作目录，列出其中的技能包候选，供「从工作目录导入」选择。画布无效返回 404。",
  },
  {
    method: "post",
    path: "/api/skills/sandbox-import",
    tag: "skills",
    auth: "local",
    successStatus: 201,
    requestSchema: sandboxSkillImportRequestSchema,
    responseSchema: skillDetailResponseSchema,
    summary: "从工作目录导入技能",
    description:
      "服务端自行读取工作目录里的技能包（不信任前端传内容），构建技能后落库并自动装进当前实例。越界或缺 SKILL.md 返回 400，同名 409。",
  },
  {
    method: "put",
    path: "/api/skills/:id",
    tag: "skills",
    auth: "local",
    successStatus: 200,
    requestSchema: skillUpdateRequestSchema,
    responseSchema: skillDetailResponseSchema,
    summary: "更新自定义技能",
    description:
      "按 id 部分更新本人创建的技能；无可更新字段返回 400，同名冲突 409，无权限或不存在 404。",
  },
  {
    method: "delete",
    path: "/api/skills/:id",
    tag: "skills",
    auth: "local",
    successStatus: 204,
    summary: "删除自定义技能",
    description: "按 id 删除本人创建的技能；不存在或无权限返回 404，成功 204。",
  },
  {
    method: "get",
    path: "/api/instance/skills",
    tag: "skills",
    auth: "local",
    successStatus: 200,
    responseSchema: instanceSkillListResponseSchema,
    summary: "列出已装实例技能",
    description: "返回当前实例已安装技能及其 enabled/installedAt 安装态信息。",
  },
  {
    method: "post",
    path: "/api/instance/skills",
    tag: "skills",
    auth: "local",
    successStatus: 204,
    summary: "安装技能到实例",
    description:
      "校验技能可见后将其安装进当前实例并启用；body.skillId 缺失返回 400，技能不可见 404，成功 204。",
  },
  {
    method: "delete",
    path: "/api/instance/skills/:skillId",
    tag: "skills",
    auth: "local",
    successStatus: 204,
    summary: "从实例卸载技能",
    description: "将指定技能从当前实例卸载；未安装返回 404，成功 204。",
  },
  {
    method: "patch",
    path: "/api/instance/skills/:skillId",
    tag: "skills",
    auth: "local",
    successStatus: 204,
    requestSchema: instanceSkillToggleRequestSchema,
    summary: "启停实例技能",
    description:
      "按 payload.enabled 切换技能在实例的启用状态；技能不可见返回 404，成功 204。",
  },
  // ---- skills-marketplace.ts（技能市场；归 skills 域）----
  {
    method: "get",
    path: "/api/skills/marketplace/search",
    tag: "skills",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({
      q: z.string().optional().describe("搜索关键词"),
      page: z.string().optional().describe("页码"),
      limit: z.string().optional().describe("每页条数"),
    }),
    summary: "搜索技能市场",
    description: "经 npm registry 搜索 skills.sh 技能市场。市场故障返回 502。",
  },
  {
    method: "get",
    path: "/api/skills/marketplace/detail",
    tag: "skills",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({ name: z.string().describe("技能包名（必填）") }),
    summary: "查询市场包详情",
    description:
      "按包名查询 npm registry 上的技能包详情。缺 name 返回 400，包不存在 404，市场故障 502。",
  },
  {
    method: "post",
    path: "/api/skills/marketplace/install",
    tag: "skills",
    auth: "local",
    successStatus: 201,
    requestSchema: marketplaceInstallRequestSchema,
    responseSchema: skillDetailResponseSchema,
    summary: "从市场安装技能",
    description:
      "按包名从 npm registry 下载并解析技能，落库（含来源与包名元数据）后自动装进当前实例。已安装 409，市场故障 502。",
  },
  // ---- system.ts（系统能力）----
  {
    method: "get",
    path: "/api/system/directory-picker",
    tag: "system",
    auth: "local",
    successStatus: 200,
    responseSchema: directoryPickerStatusSchema,
    summary: "查询目录选择器可用性",
    description:
      "返回原生目录对话框的可用状态与原因，供客户端决定走系统对话框还是回落浏览器目录选择器；非桌面形态如实报不可用。",
  },
  {
    method: "post",
    path: "/api/system/pick-directory",
    tag: "system",
    auth: "local",
    successStatus: 200,
    responseSchema: pickDirectoryResponseSchema,
    summary: "弹出原生目录选择",
    description:
      "调起原生目录对话框让用户选目录；非桌面形态不报错，返回 status=unavailable 及原因。无请求体。",
  },
  // ---- uploads.ts（资产上传）----
  {
    method: "post",
    path: "/api/uploads",
    tag: "uploads",
    auth: "local",
    successStatus: 201,
    multipart: {
      fileField: "file",
      fields: { projectId: "可选，归入指定项目" },
    },
    responseSchema: uploadResponseSchema,
    summary: "上传项目资产文件",
    description:
      "以 multipart 上传图片资产（仅 png/jpeg/webp/gif/svg，全局上限 10MB），先幂等引导实例，存入 project-assets 桶。白名单外 MIME 返回 400。",
  },
  {
    method: "get",
    path: "/api/uploads/:assetId/url",
    tag: "uploads",
    auth: "local",
    successStatus: 200,
    responseSchema: assetSignedUrlResponseSchema,
    summary: "获取资产签名 URL",
    description: "按 assetId 返回资产的签名访问 URL。",
  },
  {
    method: "delete",
    path: "/api/uploads/:assetId",
    tag: "uploads",
    auth: "local",
    successStatus: 200,
    summary: "删除资产",
    description: "按 assetId 删除资产，成功返回 200 与 { ok: true }。",
  },
  // ---- usage.ts（用量）----
  {
    method: "get",
    path: "/api/usage/summary",
    tag: "usage",
    auth: "local",
    successStatus: 200,
    responseSchema: usageSummaryResponseSchema,
    summary: "查询用量汇总",
    description: "返回当前本地实例的用量汇总（实例隔离）。",
  },
  {
    method: "get",
    path: "/api/usage/stats",
    tag: "usage",
    auth: "local",
    successStatus: 200,
    querySchema: z.object({
      days: z
        .string()
        .optional()
        .describe("统计窗口天数，仅支持 7 或 30（默认 7）"),
    }),
    responseSchema: usageStatsResponseSchema,
    summary: "查询使用统计",
    description:
      "返回用户侧使用统计。days 仅支持 7 或 30，其他值返回 400 invalid_input。",
  },
  // ---- video-models.ts（视频模型；归 models 域）----
  {
    method: "get",
    path: "/api/video-models",
    tag: "models",
    auth: "local",
    successStatus: 200,
    summary: "列出可用视频模型",
    description:
      "从用户供应商实例目录筛选 capability=video 的模型，映射为含能力/限制/计费注解的模型清单（specifier = <instanceId>:<model>），形如 { models }。",
  },
];
