// 中央路由表：服务端每个 HTTP 端点一行，是 OpenAPI spec（docs/api/openapi.json）的唯一数据源。
// 纪律：
// 1. 新增/修改路由必须同 PR 改这张表并重新生成 spec（`pnpm api:spec`），
//    漏改会被 tests/api-spec-consistency.test.mjs 的「spec ↔ 源码」对账门禁拦下。
// 2. summary/description 是面向 Apifox 的中文文档，必须非空（门禁强制）。
// 3. schema 一律引用 @kenfutwork/shared 的契约变量，禁止就地重写结构；
//    少数派生 schema（.pick / z.object 包装）内联进条目，生成时按匿名 schema 处理。
// 4. 不入 spec 的注册点：/api/ws（WebSocket，见 docs/api/ws-protocol.md）、
//    static-web 的 SPA catch-all（setNotFoundHandler，非 API）。

import {
  adminGrantCreditsRequestSchema,
  adminMeResponseSchema,
  adminPlatformUsageResponseSchema,
  adminSetRoleRequestSchema,
  adminSystemInstanceCreateRequestSchema,
  adminSystemInstanceListResponseSchema,
  adminSystemInstanceUpdateRequestSchema,
  adminUserListResponseSchema,
  agentRunActivityResponseSchema,
  agentSubagentListResponseSchema,
  apiTokenCreateRequestSchema,
  apiTokenCreateResponseSchema,
  apiTokenListResponseSchema,
  assetSignedUrlResponseSchema,
  authLoginRequestSchema,
  authRegisterRequestSchema,
  authSessionResponseSchema,
  brandKitAssetCreateRequestSchema,
  brandKitAssetResponseSchema,
  brandKitAssetUpdateRequestSchema,
  brandKitCreateRequestSchema,
  brandKitDetailResponseSchema,
  brandKitListResponseSchema,
  brandKitUpdateRequestSchema,
  canvasGetResponseSchema,
  canvasSaveRequestSchema,
  canvasSaveResponseSchema,
  chatMessageCreateRequestSchema,
  checkpointDiffResponseSchema,
  checkpointFilesResponseSchema,
  checkpointListResponseSchema,
  checkpointPreviewResponseSchema,
  checkpointRestoreFileRequestSchema,
  checkpointRestoreResponseSchema,
  claimDailyResponseSchema,
  codeFilesResponseSchema,
  codeGitBranchCreateRequestSchema,
  codeGitChangesResponseSchema,
  codeGitCheckoutRequestSchema,
  codeGitCommitRequestSchema,
  codeGitDiffResponseSchema,
  codeGitDiffStatResponseSchema,
  codeGitDiscardRequestSchema,
  codeGitDiscardResponseSchema,
  codeGitFileResponseSchema,
  codeGitGraphResponseSchema,
  codeGitStageHunkRequestSchema,
  codeGitStageRequestSchema,
  codeGitStageResponseSchema,
  codeGitStatusResponseSchema,
  codeShellsResponseSchema,
  codeTerminalRequestSchema,
  codeTerminalResponseSchema,
  codeUiEventStreamSchema,
  codeUiRpcRequestSchema,
  codeUiRpcResponseSchema,
  codeUiSnapshotResponseSchema,
  codeUiWorkspaceListSchema,
  codeWorktreeCreateRequestSchema,
  codeWorktreeListResponseSchema,
  codeWorktreeRemoveRequestSchema,
  createImageJobRequestSchema,
  createVideoJobRequestSchema,
  creditBalanceResponseSchema,
  creditTransactionsResponseSchema,
  directoryPickerStatusSchema,
  executionModeSchema,
  flowHostBillingRequestSchema,
  flowHostBillingResponseSchema,
  flowHostCredentialsRequestSchema,
  flowHostCredentialsResponseSchema,
  flowHostEventsRequestSchema,
  flowHostEventsResponseSchema,
  flowHostIdentityRequestSchema,
  flowHostIdentityResponseSchema,
  flowHostStatusResponseSchema,
  generateImageRequestSchema,
  generateVideoRequestSchema,
  healthResponseSchema,
  jobListResponseSchema,
  jobResponseSchema,
  marketplaceInstallRequestSchema,
  mcpServerCreateRequestSchema,
  mcpServerUpdateRequestSchema,
  messageCreateResponseSchema,
  messageListResponseSchema,
  modelCatalogResponseSchema,
  modelListResponseSchema,
  pickDirectoryResponseSchema,
  pluginExportRequestSchema,
  pluginInspectRequestSchema,
  pluginInspectResponseSchema,
  pluginInstallRequestSchema,
  pluginInstallResponseSchema,
  profileUpdateRequestSchema,
  profileUpdateResponseSchema,
  projectCreateRequestSchema,
  projectCreateResponseSchema,
  projectListQuerySchema,
  projectListResponseSchema,
  projectUpdateRequestSchema,
  providerInstanceCreateRequestSchema,
  providerInstanceListResponseSchema,
  providerInstanceResponseSchema,
  providerInstanceUpdateRequestSchema,
  providerPresetListResponseSchema,
  providerProbeResultSchema,
  runCancelResponseSchema,
  runCreateRequestSchema,
  runCreateResponseSchema,
  sandboxPluginBundleListResponseSchema,
  sandboxPluginInstallRequestSchema,
  sandboxSkillImportRequestSchema,
  sandboxSkillPackageListResponseSchema,
  sessionCreateResponseSchema,
  sessionListResponseSchema,
  setPlanRequestSchema,
  skillCreateRequestSchema,
  skillDetailResponseSchema,
  skillImportRequestSchema,
  skillListResponseSchema,
  skillUpdateRequestSchema,
  uploadResponseSchema,
  usageStatsResponseSchema,
  usageSummaryResponseSchema,
  viewerResponseSchema,
  workspaceSettingsResponseSchema,
  workspaceSettingsUpdateRequestSchema,
  workspaceSkillListResponseSchema,
  workspaceSkillToggleRequestSchema,
} from "@kenfutwork/shared";
import type { ZodType } from "zod";
import { z } from "zod";

/** 端点鉴权口径：user=Bearer 用户令牌；optional-user=带令牌则增强、无令牌也放行；public=完全免鉴权；shared-secret=Bearer 为服务间共享密钥（非用户令牌）。 */
export type EndpointAuth =
  | "user"
  | "optional-user"
  | "public"
  | "shared-secret";

export interface OpenApiRouteEntry {
  method: "get" | "post" | "put" | "patch" | "delete";
  /** Fastify 原样路径（:param / *），生成时转 OpenAPI {param}。 */
  path: string;
  /** 域标签，封闭清单见 tests/api-spec-consistency.test.mjs 的 CLOSED_TAGS。 */
  tag: string;
  summary: string;
  description: string;
  auth: EndpointAuth;
  successStatus: 200 | 201 | 202 | 204;
  requestSchema?: ZodType;
  querySchema?: ZodType;
  responseSchema?: ZodType;
  responseMediaType?: "text/event-stream";
  /** multipart 上传：file 为二进制字段名，fields 为附加表单字段（名 → 说明）。 */
  multipart?: { fileField: string; fields?: Record<string, string> };
  /** 成功响应为二进制时的 MIME 类型。 */
  binaryResponse?: string;
}

export const OPENAPI_ROUTES: OpenApiRouteEntry[] = [
  {
    method: "get",
    path: "/api/code-ui/events",
    tag: "code",
    auth: "user",
    successStatus: 200,
    responseSchema: codeUiEventStreamSchema,
    responseMediaType: "text/event-stream",
    summary: "订阅 Code 原协议宿主通知流",
    description:
      "认证 SSE 连接先发送原 V4 hello；RPC 使用其 connectionId 完成 clientHello 后订阅。每个 data 记录承载 ready 或原 physical wire frame，订阅初始帧在 RPC ACK 后发送，断线释放 owned 订阅。",
  },
  {
    method: "get",
    path: "/api/code-ui/workspaces",
    tag: "code",
    auth: "user",
    successStatus: 200,
    responseSchema: codeUiWorkspaceListSchema,
    summary: "查询 Code 原界面工作目录",
    description:
      "返回当前认证工作区的 Code 项目及其固定主画布工作目录，目录与 Agent、文件和 Git 共用同一解析规则。",
  },
  {
    method: "get",
    path: "/api/code-ui/sessions/:sessionId",
    tag: "code",
    auth: "user",
    successStatus: 200,
    responseSchema: codeUiSnapshotResponseSchema,
    summary: "读取 Code 主或子会话原协议快照",
    description:
      "校验会话归属后返回固定 ZCode V4 ConversationSnapshot，子会话从同一权威聚合读取独立转录。",
  },
  {
    method: "post",
    path: "/api/code-ui/rpc",
    tag: "code",
    auth: "user",
    successStatus: 200,
    requestSchema: codeUiRpcRequestSchema,
    responseSchema: codeUiRpcResponseSchema,
    summary: "调用 Code 原界面宿主接口",
    description:
      "按已接通的服务与方法白名单调用原 UI 的宿主能力。命令按 clientId 与 commandId 幂等；相同键不同参数冲突，密钥只写不读，尚未接通的方法明确拒绝。",
  },
  // ---- admin.ts（管理后台；除 /me 外均要求管理员，403 语义见 description）----
  {
    method: "get",
    path: "/api/admin/me",
    tag: "admin",
    auth: "user",
    successStatus: 200,
    responseSchema: adminMeResponseSchema,
    summary: "查询当前用户管理员身份",
    description:
      "校验令牌后返回当前用户是否为管理员，前端据此决定是否显示后台入口。仅要求登录，不要求管理员。",
  },
  {
    method: "get",
    path: "/api/admin/users",
    tag: "admin",
    auth: "user",
    successStatus: 200,
    responseSchema: adminUserListResponseSchema,
    summary: "查询平台用户列表",
    description:
      "返回全部用户及其工作区、套餐额度与用量汇总，供管理后台用户表使用。需管理员权限，非管理员返回 403。",
  },
  {
    method: "get",
    path: "/api/admin/usage",
    tag: "admin",
    auth: "user",
    successStatus: 200,
    responseSchema: adminPlatformUsageResponseSchema,
    summary: "查询平台用量总览",
    description: "返回平台级用量统计总览。需管理员权限。",
  },
  {
    method: "post",
    path: "/api/admin/users/:userId/credits",
    tag: "admin",
    auth: "user",
    successStatus: 200,
    requestSchema: adminGrantCreditsRequestSchema,
    responseSchema: adminUserListResponseSchema,
    summary: "调剂用户额度",
    description:
      "按 body 中正/负 amount 向指定用户发放或扣减额度（可附说明），随后返回刷新后的用户列表。需管理员权限。",
  },
  {
    method: "post",
    path: "/api/admin/users/:userId/plan",
    tag: "admin",
    auth: "user",
    successStatus: 200,
    requestSchema: setPlanRequestSchema,
    responseSchema: adminUserListResponseSchema,
    summary: "设置用户套餐",
    description:
      "为指定用户设置套餐，额度、并发与模型档位随之调整，返回刷新后的用户列表。需管理员权限。",
  },
  {
    method: "post",
    path: "/api/admin/users/:userId/role",
    tag: "admin",
    auth: "user",
    successStatus: 200,
    requestSchema: adminSetRoleRequestSchema,
    responseSchema: adminUserListResponseSchema,
    summary: "授予或回收管理员",
    description:
      "设置目标用户的管理员角色；拒绝对自己降级（400 invalid_action）以防锁死，返回刷新后的用户列表。需管理员权限。",
  },
  {
    method: "get",
    path: "/api/admin/providers",
    tag: "admin",
    auth: "user",
    successStatus: 200,
    responseSchema: adminSystemInstanceListResponseSchema,
    summary: "列出系统供应商实例",
    description: "返回平台池的系统级模型供应商实例清单。需管理员权限。",
  },
  {
    method: "post",
    path: "/api/admin/providers",
    tag: "admin",
    auth: "user",
    successStatus: 201,
    requestSchema: adminSystemInstanceCreateRequestSchema,
    responseSchema: providerInstanceResponseSchema,
    summary: "创建系统供应商实例",
    description:
      "创建平台池系统级模型供应商实例并记录创建人，返回实例详情。需管理员权限。",
  },
  {
    method: "patch",
    path: "/api/admin/providers/:instanceId",
    tag: "admin",
    auth: "user",
    successStatus: 200,
    requestSchema: adminSystemInstanceUpdateRequestSchema,
    responseSchema: providerInstanceResponseSchema,
    summary: "更新系统供应商实例",
    description:
      "按 instanceId 部分更新系统级供应商实例配置，返回更新后的实例。需管理员权限。",
  },
  {
    method: "delete",
    path: "/api/admin/providers/:instanceId",
    tag: "admin",
    auth: "user",
    successStatus: 204,
    summary: "删除系统供应商实例",
    description:
      "按 instanceId 删除系统级供应商实例，成功返回 204 无响应体。需管理员权限。",
  },
  // ---- api-tokens.ts（外部应用访问令牌；仅登录会话可管理，API 令牌调用回 403）----
  {
    method: "get",
    path: "/api/tokens",
    tag: "api-tokens",
    auth: "user",
    successStatus: 200,
    responseSchema: apiTokenListResponseSchema,
    summary: "列出访问令牌",
    description:
      "返回当前工作区的外部应用访问令牌清单。仅登录会话可调用，用 API 令牌调用返回 403。",
  },
  {
    method: "post",
    path: "/api/tokens",
    tag: "api-tokens",
    auth: "user",
    successStatus: 201,
    requestSchema: apiTokenCreateRequestSchema,
    responseSchema: apiTokenCreateResponseSchema,
    summary: "创建访问令牌",
    description:
      "按名称为新外部应用签发访问令牌，响应含仅此一次返回的明文 token 与记录。仅登录会话可调用。",
  },
  {
    method: "delete",
    path: "/api/tokens/:id",
    tag: "api-tokens",
    auth: "user",
    successStatus: 200,
    summary: "吊销访问令牌",
    description:
      "按 id 吊销指定访问令牌，成功返回 { ok: true }。仅登录会话可调用。",
  },
  // ---- auth.ts（口令认证；仅 KENFUTWORK_AUTH_DRIVER=managed 时挂载，local-trust 桌面形态不挂载）----
  {
    method: "post",
    path: "/api/auth/register",
    tag: "auth",
    auth: "public",
    successStatus: 201,
    requestSchema: authRegisterRequestSchema,
    responseSchema: authSessionResponseSchema,
    summary: "注册并签发会话",
    description:
      "校验邮箱与口令格式后注册新用户，直接签发会话令牌并返回用户信息。公开端点，仅 managed 认证驱动下可用。",
  },
  {
    method: "post",
    path: "/api/auth/login",
    tag: "auth",
    auth: "public",
    successStatus: 200,
    requestSchema: authLoginRequestSchema,
    responseSchema: authSessionResponseSchema,
    summary: "口令登录",
    description:
      "校验邮箱与口令，成功后签发会话令牌并返回用户信息。公开端点，仅 managed 认证驱动下可用。",
  },
  {
    method: "post",
    path: "/api/auth/logout",
    tag: "auth",
    auth: "public",
    successStatus: 204,
    summary: "登出并吊销会话",
    description:
      "解析 Bearer 令牌并吊销对应会话；幂等设计，无令牌或吊销失败也返回 204。仅 managed 认证驱动下可用。",
  },
  {
    method: "get",
    path: "/api/auth/session",
    tag: "auth",
    auth: "user",
    successStatus: 200,
    responseSchema: authSessionResponseSchema.pick({ user: true }),
    summary: "校验令牌探活会话",
    description:
      "校验 Bearer 令牌并返回当前用户信息，前端启动时用于探活；无效令牌返回 401。仅 managed 认证驱动下可用。",
  },
  // ---- blobs.ts（本地 blob 读取；仅 KENFUTWORK_BLOB_DRIVER=local 时挂载）----
  {
    method: "get",
    path: "/api/blobs/:bucket/*",
    tag: "blobs",
    auth: "public",
    successStatus: 200,
    binaryResponse: "application/octet-stream",
    summary: "读取本地 blob 对象",
    description:
      "按桶与对象路径返回本地存储文件内容（按扩展名推断 content-type）。公开桶直接放行，非公开桶要求有效 ?exp&sig HMAC 签名否则 403；越界路径按 404 处理。",
  },
  // ---- brand-kits.ts（品牌套件）----
  {
    method: "get",
    path: "/api/brand-kits",
    tag: "brand-kits",
    auth: "user",
    successStatus: 200,
    responseSchema: brandKitListResponseSchema,
    summary: "列出品牌套件",
    description: "返回当前用户可见的品牌套件清单。",
  },
  {
    method: "post",
    path: "/api/brand-kits",
    tag: "brand-kits",
    auth: "user",
    successStatus: 201,
    requestSchema: brandKitCreateRequestSchema,
    responseSchema: brandKitDetailResponseSchema,
    summary: "创建品牌套件",
    description:
      "按请求体创建新品牌套件，返回套件详情。请求体校验失败返回 400。",
  },
  {
    method: "get",
    path: "/api/brand-kits/:kitId",
    tag: "brand-kits",
    auth: "user",
    successStatus: 200,
    responseSchema: brandKitDetailResponseSchema,
    summary: "查询品牌套件详情",
    description: "按 kitId 返回品牌套件详情（含资产）。",
  },
  {
    method: "patch",
    path: "/api/brand-kits/:kitId",
    tag: "brand-kits",
    auth: "user",
    successStatus: 200,
    requestSchema: brandKitUpdateRequestSchema,
    responseSchema: brandKitDetailResponseSchema,
    summary: "更新品牌套件",
    description: "按 kitId 部分更新品牌套件信息，返回更新后的详情。",
  },
  {
    method: "post",
    path: "/api/brand-kits/:kitId/duplicate",
    tag: "brand-kits",
    auth: "user",
    successStatus: 201,
    responseSchema: brandKitDetailResponseSchema,
    summary: "复制品牌套件",
    description: "复制指定品牌套件生成新套件，返回新套件详情。无请求体。",
  },
  {
    method: "delete",
    path: "/api/brand-kits/:kitId",
    tag: "brand-kits",
    auth: "user",
    successStatus: 204,
    summary: "删除品牌套件",
    description: "删除指定品牌套件及其资产，成功返回 204。",
  },
  {
    method: "post",
    path: "/api/brand-kits/:kitId/assets/upload",
    tag: "brand-kits",
    auth: "user",
    successStatus: 201,
    multipart: {
      fileField: "file",
      fields: { asset_type: "资产类型，logo 或 image" },
    },
    responseSchema: brandKitAssetResponseSchema,
    summary: "上传品牌资产文件",
    description:
      "以 multipart 上传 logo/图片文件到指定套件；表单字段 asset_type 须为 logo 或 image，MIME 限 png/jpeg/webp/gif/svg。",
  },
  {
    method: "post",
    path: "/api/brand-kits/:kitId/assets",
    tag: "brand-kits",
    auth: "user",
    successStatus: 201,
    requestSchema: brandKitAssetCreateRequestSchema,
    responseSchema: brandKitAssetResponseSchema,
    summary: "创建品牌资产",
    description: "按请求体在套件下创建资产记录，返回资产详情。",
  },
  {
    method: "patch",
    path: "/api/brand-kits/:kitId/assets/:assetId",
    tag: "brand-kits",
    auth: "user",
    successStatus: 200,
    requestSchema: brandKitAssetUpdateRequestSchema,
    responseSchema: brandKitAssetResponseSchema,
    summary: "更新品牌资产",
    description: "按 assetId 更新套件内资产信息，返回更新后的资产。",
  },
  {
    method: "delete",
    path: "/api/brand-kits/:kitId/assets/:assetId",
    tag: "brand-kits",
    auth: "user",
    successStatus: 204,
    summary: "删除品牌资产",
    description: "删除套件内指定资产，成功返回 204。",
  },
  // ---- canvases.ts（画布）----
  {
    method: "get",
    path: "/api/canvases/:canvasId",
    tag: "canvases",
    auth: "user",
    successStatus: 200,
    responseSchema: canvasGetResponseSchema,
    summary: "读取画布内容",
    description: "按 canvasId 返回当前用户可见画布的内容与元信息。",
  },
  {
    method: "put",
    path: "/api/canvases/:canvasId",
    tag: "canvases",
    auth: "user",
    successStatus: 200,
    requestSchema: canvasSaveRequestSchema,
    responseSchema: canvasSaveResponseSchema,
    summary: "保存画布内容",
    description:
      "整体覆盖保存画布内容并返回确认。内容可含 base64 图片数据，请求体上限 50MB。",
  },
  // ---- chat.ts（会话与消息）----
  {
    method: "get",
    path: "/api/canvases/:canvasId/sessions",
    tag: "chat",
    auth: "user",
    successStatus: 200,
    responseSchema: sessionListResponseSchema,
    summary: "列出画布会话",
    description: "返回指定画布下的聊天会话列表。",
  },
  {
    method: "post",
    path: "/api/canvases/:canvasId/sessions",
    tag: "chat",
    auth: "user",
    successStatus: 201,
    responseSchema: sessionCreateResponseSchema,
    summary: "创建聊天会话",
    description: "在指定画布下新建聊天会话，可选传入 body.title 作为标题。",
  },
  {
    method: "patch",
    path: "/api/sessions/:sessionId",
    tag: "chat",
    auth: "user",
    successStatus: 200,
    summary: "重命名聊天会话",
    description:
      "更新会话标题（仅当 body.title 提供时才更新），返回 { ok: true }。",
  },
  {
    method: "delete",
    path: "/api/sessions/:sessionId",
    tag: "chat",
    auth: "user",
    successStatus: 200,
    summary: "删除聊天会话",
    description: "删除指定会话，返回 { ok: true }。",
  },
  {
    method: "get",
    path: "/api/sessions/:sessionId/messages",
    tag: "chat",
    auth: "user",
    successStatus: 200,
    responseSchema: messageListResponseSchema,
    summary: "列出会话消息",
    description: "返回指定会话的消息列表。",
  },
  {
    method: "post",
    path: "/api/sessions/:sessionId/messages",
    tag: "chat",
    auth: "user",
    successStatus: 201,
    requestSchema: chatMessageCreateRequestSchema,
    responseSchema: messageCreateResponseSchema,
    summary: "追加会话消息",
    description:
      "向会话追加一条消息（可含 base64 画布选区图片），返回新消息。请求体上限 10MB。",
  },
  // ---- checkpoints.ts（代码模式：检查点）----
  {
    method: "get",
    path: "/api/code/checkpoints",
    tag: "code",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({ canvasId: z.string().describe("画布 ID（必填）") }),
    responseSchema: checkpointListResponseSchema,
    summary: "列出画布检查点",
    description:
      "按 canvasId 返回画布的检查点时间线（升序）。canvasId 为必填查询参数，缺失返回 400。",
  },
  {
    method: "get",
    path: "/api/code/checkpoints/:checkpointId/diff",
    tag: "code",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({
      path: z.string().optional().describe("限定单文件的相对路径（可选）"),
    }),
    responseSchema: checkpointDiffResponseSchema,
    summary: "查询检查点差异",
    description:
      "返回该检查点相对上一检查点的统一 diff，可用 path 限定单文件。",
  },
  {
    method: "post",
    path: "/api/code/checkpoints/:checkpointId/preview",
    tag: "code",
    auth: "user",
    successStatus: 200,
    responseSchema: checkpointPreviewResponseSchema,
    summary: "预览恢复影响",
    description: "返回回滚到该检查点将受影响的文件清单，供二次确认。无请求体。",
  },
  {
    method: "post",
    path: "/api/code/checkpoints/:checkpointId/restore",
    tag: "code",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({ canvasId: z.string().describe("画布 ID（必填）") }),
    responseSchema: checkpointRestoreResponseSchema,
    summary: "回滚到检查点",
    description:
      "将画布工作目录回滚到指定检查点（丢内容操作）。存在在途 run 时返回 409 run_in_progress。",
  },
  {
    method: "get",
    path: "/api/code/checkpoints/:checkpointId/files",
    tag: "code",
    auth: "user",
    successStatus: 200,
    responseSchema: checkpointFilesResponseSchema,
    summary: "列出轮次文件变更",
    description: "返回该检查点对应轮次的逐文件变更清单。",
  },
  {
    method: "post",
    path: "/api/code/checkpoints/:checkpointId/restore-file",
    tag: "code",
    auth: "user",
    successStatus: 200,
    requestSchema: checkpointRestoreFileRequestSchema,
    querySchema: z.object({ canvasId: z.string().describe("画布 ID（必填）") }),
    responseSchema: checkpointRestoreResponseSchema,
    summary: "撤销单文件变更",
    description:
      "将单个文件恢复到检查点状态；body 需 path，canvasId 为必填查询参数，存在在途 run 时返回 409。",
  },
  // ---- code-git.ts（代码模式：git 与工作目录）----
  {
    method: "get",
    path: "/api/code/git",
    tag: "code",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({ canvasId: z.string().describe("画布 ID（必填）") }),
    responseSchema: codeGitStatusResponseSchema,
    summary: "查询 git 状态",
    description:
      "按 canvasId 返回项目工作目录的 git 状态（分支、暂存、变更等）。canvasId 必填，缺失返回 400。",
  },
  {
    method: "post",
    path: "/api/code/git/checkout",
    tag: "code",
    auth: "user",
    successStatus: 200,
    requestSchema: codeGitCheckoutRequestSchema,
    responseSchema: codeGitStatusResponseSchema,
    summary: "切换 git 分支",
    description: "将项目工作目录切换到指定分支，返回最新 git 状态。",
  },
  {
    method: "get",
    path: "/api/code/git/diff-stat",
    tag: "code",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({ canvasId: z.string().describe("画布 ID（必填）") }),
    responseSchema: codeGitDiffStatResponseSchema,
    summary: "查询变更统计",
    description: "返回工作目录相对 HEAD 的增删行数统计。canvasId 必填。",
  },
  {
    method: "get",
    path: "/api/code/git/graph",
    tag: "code",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({
      canvasId: z.string().describe("画布 ID（必填）"),
      limit: z
        .string()
        .optional()
        .describe("返回条数上限，服务端夹取到 1..200（默认 30）"),
    }),
    responseSchema: codeGitGraphResponseSchema,
    summary: "查询 git 图谱",
    description: "返回提交图谱。canvasId 必填；limit 由服务端夹取到 1..200。",
  },
  {
    method: "get",
    path: "/api/code/git/changes",
    tag: "code",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({ canvasId: z.string().describe("画布 ID（必填）") }),
    responseSchema: codeGitChangesResponseSchema,
    summary: "列出变更文件清单",
    description:
      "逐文件返回变更状态与增删行数，最多 200 个（超出截断并标注）。canvasId 必填。",
  },
  {
    method: "get",
    path: "/api/code/git/diff",
    tag: "code",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({
      canvasId: z.string().describe("画布 ID（必填）"),
      path: z.string().describe("工作目录内文件相对路径（必填）"),
    }),
    responseSchema: codeGitDiffResponseSchema,
    summary: "查询单文件差异",
    description:
      "返回指定工作目录文件的统一 diff。canvasId 与 path 均必填，缺失返回 400。",
  },
  {
    method: "get",
    path: "/api/code/file",
    tag: "code",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({
      canvasId: z.string().describe("画布 ID（必填）"),
      path: z.string().describe("工作目录内文件相对路径（必填）"),
    }),
    responseSchema: codeGitFileResponseSchema,
    summary: "读取工作目录文件",
    description:
      "只读预览工作目录内单个文件：路径必须落在工作目录内、最多前 256KB，二进制文件只回元信息。",
  },
  {
    method: "get",
    path: "/api/code/files",
    tag: "code",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({
      canvasId: z.string().describe("画布 ID（必填）"),
      path: z.string().optional().describe("目录相对路径（可选，默认根目录）"),
    }),
    responseSchema: codeFilesResponseSchema,
    summary: "列出工作目录文件",
    description:
      "列出工作目录指定层级的文件与子目录（只列一层）。canvasId 必填。",
  },
  {
    method: "post",
    path: "/api/code/terminal",
    tag: "code",
    auth: "user",
    successStatus: 200,
    requestSchema: codeTerminalRequestSchema,
    responseSchema: codeTerminalResponseSchema,
    summary: "执行终端命令",
    description:
      "在画布工作目录里执行一条用户命令（固定 cwd、有超时与输出上限），返回执行结果。",
  },
  {
    method: "post",
    path: "/api/code/git/stage",
    tag: "code",
    auth: "user",
    successStatus: 200,
    requestSchema: codeGitStageRequestSchema,
    responseSchema: codeGitStageResponseSchema,
    summary: "暂存或取消暂存文件",
    description: "设置单个文件的暂存状态，返回该文件最新状态。",
  },
  {
    method: "post",
    path: "/api/code/git/stage-hunk",
    tag: "code",
    auth: "user",
    successStatus: 200,
    requestSchema: codeGitStageHunkRequestSchema,
    responseSchema: codeGitStageResponseSchema,
    summary: "暂存或取消暂存块",
    description:
      "按 patch 暂存或反应用单个 diff 块（可选 reverse/target），返回文件暂存状态。",
  },
  {
    method: "post",
    path: "/api/code/git/discard",
    tag: "code",
    auth: "user",
    successStatus: 200,
    requestSchema: codeGitDiscardRequestSchema,
    responseSchema: codeGitDiscardResponseSchema,
    summary: "撤销工作区更改",
    description:
      "撤销单文件（payload.path 存在时，可含未跟踪文件）或全部未提交更改。丢内容操作，界面需二次确认。",
  },
  {
    method: "get",
    path: "/api/code/shells",
    tag: "code",
    auth: "user",
    successStatus: 200,
    responseSchema: codeShellsResponseSchema,
    summary: "列出可用 shell",
    description:
      "返回本机可用的 shell 清单与工作区默认项，供终端下拉与设置页共用。",
  },
  {
    method: "post",
    path: "/api/code/git/init",
    tag: "code",
    auth: "user",
    successStatus: 200,
    requestSchema: codeGitCheckoutRequestSchema.pick({ canvasId: true }),
    responseSchema: codeGitStatusResponseSchema,
    summary: "初始化 git 仓库",
    description: "在非仓库的工作目录上幂等初始化 git 仓库，返回最新状态。",
  },
  {
    method: "post",
    path: "/api/code/git/commit",
    tag: "code",
    auth: "user",
    successStatus: 200,
    requestSchema: codeGitCommitRequestSchema,
    responseSchema: codeGitStatusResponseSchema,
    summary: "提交暂存更改",
    description: "以给定 message 提交暂存内容，返回最新 git 状态。",
  },
  {
    method: "post",
    path: "/api/code/git/push",
    tag: "code",
    auth: "user",
    successStatus: 200,
    requestSchema: codeGitCheckoutRequestSchema.pick({ canvasId: true }),
    responseSchema: codeGitStatusResponseSchema,
    summary: "推送提交到远端",
    description: "将当前分支推送到远端仓库，返回最新 git 状态。",
  },
  {
    method: "get",
    path: "/api/code/git/worktrees",
    tag: "code",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({ canvasId: z.string().describe("画布 ID（必填）") }),
    responseSchema: codeWorktreeListResponseSchema,
    summary: "列出 git 工作树",
    description: "返回项目关联的 git 工作树清单。canvasId 必填。",
  },
  {
    method: "post",
    path: "/api/code/git/worktrees",
    tag: "code",
    auth: "user",
    successStatus: 200,
    requestSchema: codeWorktreeCreateRequestSchema,
    responseSchema: codeWorktreeListResponseSchema,
    summary: "新建 git 工作树",
    description: "按 path/branch/create 参数新建工作树，返回最新工作树清单。",
  },
  {
    method: "post",
    path: "/api/code/git/worktrees/remove",
    tag: "code",
    auth: "user",
    successStatus: 200,
    requestSchema: codeWorktreeRemoveRequestSchema,
    responseSchema: codeWorktreeListResponseSchema,
    summary: "删除 git 工作树",
    description: "按 path 删除工作树（可 force 强制），返回最新工作树清单。",
  },
  {
    method: "post",
    path: "/api/code/git/branch",
    tag: "code",
    auth: "user",
    successStatus: 200,
    requestSchema: codeGitBranchCreateRequestSchema,
    responseSchema: codeGitStatusResponseSchema,
    summary: "新建 git 分支",
    description: "以给定名称在项目仓库创建分支，返回最新 git 状态。",
  },
  // ---- code-index.ts（代码模式：索引；响应为裸对象，未过 zod）----
  {
    method: "get",
    path: "/api/code/index",
    tag: "code",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({ canvasId: z.string().describe("画布 ID（必填）") }),
    summary: "查询索引状态",
    description:
      "返回画布工作目录的索引统计及该工作区的两个开关（codeIndexEnabled、codeIndexAutoNewFolder）。canvasId 必填。",
  },
  {
    method: "post",
    path: "/api/code/index/rebuild",
    tag: "code",
    auth: "user",
    successStatus: 200,
    summary: "重建代码索引",
    description:
      "重新扫描工作目录并重建索引，返回新统计。body 中 canvasId 必填。",
  },
  {
    method: "delete",
    path: "/api/code/index",
    tag: "code",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({ canvasId: z.string().describe("画布 ID（必填）") }),
    summary: "清空代码索引",
    description:
      "删除该画布的索引缓存文件（本机 <cwd>/.kenfutwork/index/ 下的 JSON），返回 { ok: true }。canvasId 必填。",
  },
  {
    method: "get",
    path: "/api/code/index/search",
    tag: "code",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({
      canvasId: z.string().describe("画布 ID（必填）"),
      q: z.string().describe("搜索关键词（必填）"),
    }),
    summary: "搜索代码索引",
    description:
      "在索引内即时搜索并返回命中与构建时间。索引开关未开返回 409 index_disabled，无索引返回 409 index_not_built，索引过大返回 413 index_too_large。",
  },
  // ---- credits.ts（积分额度）----
  {
    method: "get",
    path: "/api/credits",
    tag: "credits",
    auth: "user",
    successStatus: 200,
    responseSchema: creditBalanceResponseSchema,
    summary: "查询额度余额",
    description:
      "返回当前工作区积分余额、套餐及并发/分辨率/月度/日度限额配置。",
  },
  {
    method: "get",
    path: "/api/credits/transactions",
    tag: "credits",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({
      limit: z
        .string()
        .optional()
        .describe("返回条数上限（默认 20，最大 100）"),
    }),
    responseSchema: creditTransactionsResponseSchema,
    summary: "查询额度流水",
    description: "返回最近的积分交易流水；limit 上限 100（默认 20）。",
  },
  {
    method: "post",
    path: "/api/credits/claim-daily",
    tag: "credits",
    auth: "user",
    successStatus: 200,
    responseSchema: claimDailyResponseSchema,
    summary: "领取每日免费额度",
    description:
      "领取当日免费积分；已领取或套餐不可领时仍返回 200（success=false 附提示语）。无请求体。",
  },
  {
    method: "post",
    path: "/api/credits/admin/set-plan",
    tag: "credits",
    auth: "user",
    successStatus: 200,
    requestSchema: setPlanRequestSchema,
    responseSchema: creditBalanceResponseSchema,
    summary: "切换工作区套餐",
    description:
      "切换当前工作区套餐并返回刷新后的余额与限额。开发期调试端点（未接管理员门），正式部署慎开放。",
  },
  // ---- execution-modes.ts（执行模式）----
  {
    method: "get",
    path: "/api/execution-modes",
    tag: "execution-modes",
    auth: "user",
    successStatus: 200,
    summary: "列出执行模式",
    description: "返回六档执行模式词汇表，形如 { modes: [...] }。",
  },
  {
    method: "get",
    path: "/api/execution-modes/:threadId",
    tag: "execution-modes",
    auth: "user",
    successStatus: 200,
    responseSchema: executionModeSchema,
    summary: "查询线程激活模式",
    description: "返回线程当前激活的执行模式；缓存未命中时回读持久化值。",
  },
  {
    method: "put",
    path: "/api/execution-modes/:threadId",
    tag: "execution-modes",
    auth: "user",
    successStatus: 200,
    requestSchema: z.object({
      mode: executionModeSchema.describe("要激活的执行模式"),
    }),
    summary: "切换线程执行模式",
    description:
      "激活并写穿持久化线程执行模式，返回 { mode }。会话不属当前工作区返回 404；请求非法返回 400。",
  },
  // ---- flow-host.ts（flow 集成宿主缝；credentials/billing/events 用共享密钥而非用户令牌）----
  {
    method: "get",
    path: "/api/flow/host/status",
    tag: "flow",
    auth: "user",
    successStatus: 200,
    responseSchema: flowHostStatusResponseSchema,
    summary: "查询 flow 宿主启用状态",
    description:
      "返回 flow 宿主能力是否启用，并附未启用原因（缺共享密钥或前端地址配置）。未配置时也返回 200 + enabled=false。",
  },
  {
    method: "get",
    path: "/api/flow/host/engine",
    tag: "flow",
    auth: "user",
    successStatus: 200,
    summary: "探测 flow 引擎承载环境",
    description:
      "只读探测引擎可承载路径（平台 / WSL2 / 本机容器 / 自管地址），不做安装、下载或拉起。",
  },
  {
    method: "post",
    path: "/api/flow/host/credentials",
    tag: "flow",
    auth: "shared-secret",
    successStatus: 200,
    requestSchema: flowHostCredentialsRequestSchema,
    responseSchema: flowHostCredentialsResponseSchema,
    summary: "下发 Dify 引擎凭证",
    description:
      "校验共享密钥后，从平台池解析启用的 dify-engine 实例，向 flow 网关下发引擎地址与明文 API Key。未配密钥 503，无可用实例 404，base_url 缺失或非法 409。",
  },
  {
    method: "post",
    path: "/api/flow/host/billing",
    tag: "flow",
    auth: "shared-secret",
    successStatus: 200,
    requestSchema: flowHostBillingRequestSchema,
    responseSchema: flowHostBillingResponseSchema,
    summary: "处理 flow 计费三段事务",
    description:
      "按 op（reserve/settle/refund）执行积分预扣、结算或退款事务，用 hostSubject 解析宿主用户与个人工作区归属。归属解析失败 409 flow_billing_conflict。",
  },
  {
    method: "post",
    path: "/api/flow/host/events",
    tag: "flow",
    auth: "shared-secret",
    successStatus: 200,
    requestSchema: flowHostEventsRequestSchema,
    responseSchema: flowHostEventsResponseSchema,
    summary: "接收 flow 运行事件批次",
    description:
      "校验共享密钥后逐条解析事件归属，经 WebSocket 通道投递 flowRun.event；无法归属或契约不过的事件跳过并计数。批次可跨 run / 跨用户。",
  },
  {
    method: "post",
    path: "/api/flow/host/identity",
    tag: "flow",
    auth: "shared-secret",
    successStatus: 200,
    requestSchema: flowHostIdentityRequestSchema,
    responseSchema: flowHostIdentityResponseSchema,
    summary: "交换宿主用户身份",
    description:
      "先验共享密钥，再用请求体里的宿主会话令牌验证登录用户，返回 subject、显示名与邮箱供 flow 侧建号。未配密钥 503，令牌无效 401。",
  },
  // ---- fonts.ts（字体；免鉴权）----
  {
    method: "get",
    path: "/api/fonts",
    tag: "fonts",
    auth: "public",
    successStatus: 200,
    querySchema: z.object({
      search: z.string().optional().describe("按字体族名称过滤"),
      category: z.string().optional().describe("按类别过滤"),
    }),
    summary: "检索谷歌字体列表",
    description:
      "代理 Google Fonts API 并做 24 小时内存缓存。未配置上游密钥或上游失败时返回空列表或旧缓存。",
  },
  // ---- generate.ts（同步生成）----
  {
    method: "post",
    path: "/api/agent/generate-image",
    tag: "generate",
    auth: "user",
    successStatus: 200,
    requestSchema: generateImageRequestSchema,
    summary: "同步生成图片并入库",
    description:
      "按套餐做模型/分辨率/并发校验并预扣积分，经 BYOK 实例图像适配器生成，结果下载转存对象存储后返回签名 URL 与资产 id。缺 providerInstanceId 或 model 返回 400；上游失败 502。",
  },
  {
    method: "post",
    path: "/api/agent/generate-video",
    tag: "generate",
    auth: "user",
    successStatus: 202,
    requestSchema: generateVideoRequestSchema,
    summary: "受理视频生成任务",
    description:
      "校验套餐与积分后创建 video_generation 任务并预扣积分，由 worker 异步执行，进度经 GET /api/jobs/{jobId} 轮询。返回 { job_id, status, prompt }。",
  },
  // ---- health.ts（健康检查；免鉴权）----
  {
    method: "get",
    path: "/api/health",
    tag: "health",
    auth: "public",
    successStatus: 200,
    responseSchema: healthResponseSchema,
    summary: "检查服务健康状态",
    description: "健康探针，返回服务名 kenfutwork-server 与版本号。",
  },
  // ---- image-models.ts / video-models.ts / model-catalog.ts / models.ts（模型）----
  {
    method: "get",
    path: "/api/image-models",
    tag: "models",
    auth: "user",
    successStatus: 200,
    summary: "列出可用图像模型",
    description:
      "从登录用户的供应商实例目录筛选具备 image / image-edit 能力的模型，specifier 形如 <instanceId>:<model>。BYOK-only：内置图像模型目录已退役。",
  },
  {
    method: "get",
    path: "/api/proxy-image",
    tag: "image-proxy",
    auth: "public",
    successStatus: 200,
    querySchema: z.object({
      url: z.string().describe("要代理拉取的外部图片 URL"),
    }),
    binaryResponse: "image/*",
    summary: "代理拉取外部图片",
    description:
      "服务端转发白名单域名的外部图片，绕过浏览器 CORS 限制。白名单 = replicate 系列域名 + KENFUTWORK_IMAGE_PROXY_ALLOWED_HOSTS；非法 url 400、域名不允许 403、上游失败透传或 502。",
  },
  // ---- jobs.ts（后台任务）----
  {
    method: "post",
    path: "/api/jobs/image-generation",
    tag: "jobs",
    auth: "user",
    successStatus: 201,
    requestSchema: createImageJobRequestSchema,
    responseSchema: jobResponseSchema,
    summary: "创建图片生成任务",
    description:
      "校验套餐模型访问与并发后创建 image_generation 任务并扣减积分，扣费失败自动取消任务。",
  },
  {
    method: "post",
    path: "/api/jobs/video-generation",
    tag: "jobs",
    auth: "user",
    successStatus: 201,
    requestSchema: createVideoJobRequestSchema,
    responseSchema: jobResponseSchema,
    summary: "创建视频生成任务",
    description:
      "创建 video_generation 任务并预扣积分，支持时长、分辨率、宽高比、参考图/参考视频等参数透传给 worker。",
  },
  {
    method: "get",
    path: "/api/jobs/:jobId",
    tag: "jobs",
    auth: "user",
    successStatus: 200,
    responseSchema: jobResponseSchema,
    summary: "查询单个任务状态",
    description:
      "按 jobId 返回当前用户的任务详情，供客户端轮询异步任务进度。不存在返回 404。",
  },
  {
    method: "get",
    path: "/api/jobs",
    tag: "jobs",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({
      status: z.string().optional().describe("按任务状态过滤（可选）"),
      job_type: z.string().optional().describe("按任务类型过滤（可选）"),
    }),
    responseSchema: jobListResponseSchema,
    summary: "列出当前用户任务",
    description:
      "返回当前用户任务列表，支持 status 与 job_type 两个可选查询参数过滤。",
  },
  {
    method: "post",
    path: "/api/jobs/:jobId/cancel",
    tag: "jobs",
    auth: "user",
    successStatus: 200,
    responseSchema: jobResponseSchema,
    summary: "取消未完成任务",
    description: "取消指定任务并返回取消后的任务状态。",
  },
  // ---- mcp.ts（MCP 服务器；变更类操作需管理员）----
  {
    method: "get",
    path: "/api/mcp/servers",
    tag: "mcp",
    auth: "user",
    successStatus: 200,
    summary: "列出 MCP 服务器状态",
    description:
      "返回已配置 MCP server 的配置键名与运行状态（不含密钥值），形如 { servers }。",
  },
  {
    method: "get",
    path: "/api/mcp/catalog",
    tag: "mcp",
    auth: "user",
    successStatus: 200,
    summary: "获取精选 MCP 目录",
    description: "返回内置精选 MCP server 目录（离线可用），供前端一键添加。",
  },
  {
    method: "get",
    path: "/api/mcp/registry",
    tag: "mcp",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({
      q: z.string().optional().describe("按名称子串检索（默认空）"),
      limit: z.string().optional().describe("返回条数上限（默认 20）"),
    }),
    summary: "检索官方 MCP 注册表",
    description:
      "代理官方 MCP Registry 的 search 检索。上游不可用返回 502 mcp_registry_unavailable。",
  },
  {
    method: "post",
    path: "/api/mcp/servers",
    tag: "mcp",
    auth: "user",
    successStatus: 201,
    requestSchema: mcpServerCreateRequestSchema,
    summary: "新增 MCP 服务器",
    description:
      "创建 MCP server 配置；连接失败不报错（状态里可查原因），同名已存在返回 409。需管理员权限，非管理员 403。",
  },
  {
    method: "patch",
    path: "/api/mcp/servers/:id",
    tag: "mcp",
    auth: "user",
    successStatus: 200,
    requestSchema: mcpServerUpdateRequestSchema,
    summary: "更新 MCP 服务器配置",
    description:
      "部分更新指定 server 的配置或启停，改完自动重连收敛；不存在返回 404。需管理员权限。",
  },
  {
    method: "delete",
    path: "/api/mcp/servers/:id",
    tag: "mcp",
    auth: "user",
    successStatus: 204,
    summary: "删除 MCP 服务器",
    description:
      "删除指定 server 配置并断开其 stdio 子进程连接；不存在返回 404。需管理员权限。",
  },
  {
    method: "post",
    path: "/api/mcp/servers/:id/reconnect",
    tag: "mcp",
    auth: "user",
    successStatus: 200,
    summary: "手动重连 MCP 服务器",
    description:
      "触发指定 server 手动重连并返回最新运行状态；不存在返回 404。需管理员权限。",
  },
  {
    method: "get",
    path: "/api/model-catalog",
    tag: "models",
    auth: "user",
    successStatus: 200,
    responseSchema: modelCatalogResponseSchema,
    summary: "获取动态模型目录",
    description:
      "从登录用户的供应商实例推导完整模型目录（覆盖各能力模型）。目录读取失败统一 500。",
  },
  {
    method: "get",
    path: "/api/models",
    tag: "models",
    auth: "optional-user",
    successStatus: 200,
    responseSchema: modelListResponseSchema,
    summary: "列出对话模型清单",
    description:
      "返回内置 OpenAI/Google 模型（按环境变量密钥存在与否裁剪），携带有效令牌时并入该用户 BYOK 实例的 chat 模型；未登录仅返回内置清单。",
  },
  // ---- payments.ts（订阅支付；webhook 见下）----
  {
    method: "post",
    path: "/api/payments/checkout",
    tag: "payments",
    auth: "user",
    successStatus: 200,
    summary: "创建支付结账会话",
    description:
      "校验套餐（plan）与计费周期（billingPeriod）后创建 Lemon Squeezy checkout，返回 checkoutUrl；free 套餐拒绝创建。body 无整体 schema，字段级按枚举校验。",
  },
  {
    method: "get",
    path: "/api/payments/subscription",
    tag: "payments",
    auth: "user",
    successStatus: 200,
    summary: "查询当前订阅状态",
    description: "返回当前工作区的订阅套餐、计费周期与状态。",
  },
  {
    method: "post",
    path: "/api/payments/cancel",
    tag: "payments",
    auth: "user",
    successStatus: 200,
    summary: "取消订阅（期末生效）",
    description:
      "将当前订阅标记为计费周期末取消，成功返回 success: true。无请求体。",
  },
  {
    method: "post",
    path: "/api/payments/change-plan",
    tag: "payments",
    auth: "user",
    successStatus: 200,
    summary: "变更订阅套餐",
    description:
      "将当前订阅切换到目标套餐与计费周期，free 套餐被拒绝（应改走取消）。body 字段级按枚举校验。",
  },
  {
    method: "post",
    path: "/api/payments/webhook",
    tag: "payments",
    auth: "public",
    successStatus: 200,
    summary: "接收支付回调事件",
    description:
      "验证 X-Signature 头（HMAC-SHA256）后将事件落 payment_events 审计表，并分发处理 Lemon Squeezy 订阅/支付事件。处理失败仍返回 200 以避免上游无限重试。供 Lemon Squeezy 服务端回调调用。",
  },
  // ---- permissions.ts（权限档位）----
  {
    method: "get",
    path: "/api/permissions/tier",
    tag: "permissions",
    auth: "user",
    successStatus: 200,
    summary: "查询权限档位设置",
    description:
      "返回权限档位、自动化档位、自定义规则、浏览器控制相关开关及永久放行工具清单。",
  },
  {
    method: "put",
    path: "/api/permissions/tier",
    tag: "permissions",
    auth: "user",
    successStatus: 200,
    summary: "部分更新权限设置",
    description:
      "只更新请求送来的字段（tier/automationTier/rules 及若干布尔开关），先写库成功后再改内存，返回与 GET 相同形状。",
  },
  {
    method: "post",
    path: "/api/permissions/approve",
    tag: "permissions",
    auth: "user",
    successStatus: 204,
    summary: "人审放行工具调用",
    description:
      "对指定工具（body.toolName）按 scope（once/thread/forever）做人工放行授权，成功无响应体；缺 toolName 返回 400。agent 无自我授权路径，此端点是唯一人审入口。",
  },
  // ---- plugins.ts（插件；变更类操作需管理员）----
  {
    method: "get",
    path: "/api/plugins",
    tag: "plugins",
    auth: "user",
    successStatus: 200,
    summary: "列出已安装插件",
    description: "返回本实例已安装插件的清单，供插件市场面板展示。",
  },
  {
    method: "post",
    path: "/api/plugins/inspect",
    tag: "plugins",
    auth: "user",
    successStatus: 200,
    requestSchema: pluginInspectRequestSchema,
    responseSchema: pluginInspectResponseSchema,
    summary: "预检插件兼容性",
    description:
      "只校验插件来源与兼容性门禁，不落盘不装载；让 UI 在用户点安装前看到门禁结论。来源拉取失败 502。",
  },
  {
    method: "post",
    path: "/api/plugins/install",
    tag: "plugins",
    auth: "user",
    successStatus: 201,
    requestSchema: pluginInstallRequestSchema,
    responseSchema: pluginInstallResponseSchema,
    summary: "安装插件",
    description:
      "拉取并安装第三方插件，安装前过兼容性门禁，未通过返回 422 及完整报告。body 含 builtin 字段时走内置安装分支。需管理员权限。",
  },
  {
    method: "get",
    path: "/api/plugins/sandbox-bundles",
    tag: "plugins",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({ canvasId: z.string().describe("画布 ID（必填）") }),
    responseSchema: sandboxPluginBundleListResponseSchema,
    summary: "列出工作目录插件包",
    description:
      "按 canvasId 解析画布归属的工作目录，列出其中的插件 bundle 候选，供「从工作目录安装」选择。画布无效返回 404。",
  },
  {
    method: "post",
    path: "/api/plugins/sandbox-install",
    tag: "plugins",
    auth: "user",
    successStatus: 201,
    requestSchema: sandboxPluginInstallRequestSchema,
    responseSchema: pluginInstallResponseSchema,
    summary: "从工作目录安装插件",
    description:
      "把工作目录里的 bundle 目录安装到本实例，禁止生命周期脚本；响应形状与 /api/plugins/install 一致。需管理员权限。",
  },
  {
    method: "get",
    path: "/api/plugins/:pluginId/assets/*",
    tag: "plugins",
    auth: "public",
    successStatus: 200,
    summary: "读取插件静态资源",
    description:
      "公开只读地返回插件声明的静态资源（面板 iframe 可直接加载）；仅在插件清单声明 assets 时开放，越界或缺失一律 404。",
  },
  {
    method: "get",
    path: "/api/plugins/:pluginId/*",
    tag: "plugins",
    auth: "user",
    successStatus: 200,
    summary: "派发插件自定义路由（GET）",
    description:
      "把请求派发给插件运行时注册的路由处理器；默认要求登录，插件可显式声明 public 开放。实际状态码由插件返回决定。",
  },
  {
    method: "post",
    path: "/api/plugins/:pluginId/*",
    tag: "plugins",
    auth: "user",
    successStatus: 200,
    summary: "派发插件自定义路由（POST）",
    description:
      "与 GET 同一派发逻辑，处理插件自定义的 POST 路由；body 与 headers 原样转交插件。实际状态码由插件返回决定。",
  },
  {
    method: "post",
    path: "/api/plugins/:id/uninstall",
    tag: "plugins",
    auth: "user",
    successStatus: 200,
    summary: "卸载插件",
    description:
      "按 id 卸载插件；系统插件返回 403，未安装返回 404。响应 { id, installed: false }。需管理员权限。",
  },
  {
    method: "post",
    path: "/api/plugins/:id/toggle",
    tag: "plugins",
    auth: "user",
    successStatus: 200,
    summary: "切换插件启停",
    description:
      "按 id 启用/禁用插件，body.enabled 必须为布尔值；未安装返回 404。需管理员权限。",
  },
  {
    method: "post",
    path: "/api/plugins/export",
    tag: "plugins",
    auth: "user",
    successStatus: 200,
    requestSchema: pluginExportRequestSchema,
    summary: "导出插件 bundle 骨架",
    description:
      "按名称与格式生成双声明插件 bundle 骨架，不落盘，由客户端决定保存位置。",
  },
  // ---- projects.ts（项目）----
  {
    method: "get",
    path: "/api/projects/:projectId",
    tag: "projects",
    auth: "user",
    successStatus: 200,
    summary: "查询单个项目",
    description: "按 projectId 返回当前用户可见的项目详情，形如 { project }。",
  },
  {
    method: "get",
    path: "/api/projects",
    tag: "projects",
    auth: "user",
    successStatus: 200,
    querySchema: projectListQuerySchema,
    responseSchema: projectListResponseSchema,
    summary: "列出项目",
    description: "按 kind（design/code/flow）过滤列出当前用户可见的项目列表。",
  },
  {
    method: "delete",
    path: "/api/projects/:projectId",
    tag: "projects",
    auth: "user",
    successStatus: 204,
    summary: "归档（软删）项目",
    description: "归档指定项目（非物理删除），成功返回 204 无响应体。",
  },
  {
    method: "post",
    path: "/api/projects",
    tag: "projects",
    auth: "user",
    successStatus: 201,
    requestSchema: projectCreateRequestSchema,
    responseSchema: projectCreateResponseSchema,
    summary: "创建项目",
    description:
      "按请求体创建新项目并返回创建结果。请求体校验失败返回 400 带 issues。",
  },
  {
    method: "patch",
    path: "/api/projects/:projectId",
    tag: "projects",
    auth: "user",
    successStatus: 204,
    requestSchema: projectUpdateRequestSchema,
    summary: "更新项目",
    description:
      "部分更新项目字段，成功返回 204 无响应体。请求体校验失败返回 400 带 issues。",
  },
  {
    method: "put",
    path: "/api/projects/:projectId/thumbnail",
    tag: "projects",
    auth: "user",
    successStatus: 200,
    multipart: { fileField: "file" },
    summary: "上传项目缩略图",
    description:
      "以 multipart 表单上传项目缩略图文件（上限 2MB），缺省 MIME 按 image/webp 处理并保存。",
  },
  // ---- provider-instances.ts（BYOK 供应商实例；apiKey 只写不读）----
  {
    method: "get",
    path: "/api/provider-instances",
    tag: "provider-instances",
    auth: "user",
    successStatus: 200,
    responseSchema: providerInstanceListResponseSchema,
    summary: "列出供应商实例",
    description:
      "列出当前用户的模型供应商实例；只含 hasCredential 布尔，永不回传 apiKey。",
  },
  {
    method: "post",
    path: "/api/provider-instances",
    tag: "provider-instances",
    auth: "user",
    successStatus: 201,
    requestSchema: providerInstanceCreateRequestSchema,
    responseSchema: providerInstanceResponseSchema,
    summary: "创建供应商实例",
    description:
      "创建供应商实例，apiKey 只写不读；非法头名/保留头/CRLF 等校验失败返回 400。",
  },
  {
    method: "patch",
    path: "/api/provider-instances/:instanceId",
    tag: "provider-instances",
    auth: "user",
    successStatus: 200,
    requestSchema: providerInstanceUpdateRequestSchema,
    responseSchema: providerInstanceResponseSchema,
    summary: "更新供应商实例",
    description: "更新供应商实例配置；apiKey 缺省即不改，传入即覆盖。",
  },
  {
    method: "get",
    path: "/api/provider-instances/presets",
    tag: "provider-instances",
    auth: "public",
    successStatus: 200,
    responseSchema: providerPresetListResponseSchema,
    summary: "列出供应商预设",
    description:
      "返回 models.dev 供应商预设（供「从预设选择」）；非权威 UI 数据，capability 由模态推导，用户可改。公开端点。",
  },
  {
    method: "post",
    path: "/api/provider-instances/:instanceId/probe",
    tag: "provider-instances",
    auth: "user",
    successStatus: 200,
    responseSchema: providerProbeResultSchema,
    summary: "探测实例连通能力",
    description:
      "对指定实例做连通性与中转方言四项探测，结果缓存到实例，运行期据此裁剪请求。无请求体。",
  },
  {
    method: "delete",
    path: "/api/provider-instances/:instanceId",
    tag: "provider-instances",
    auth: "user",
    successStatus: 204,
    summary: "删除供应商实例",
    description: "删除指定供应商实例，成功返回 204 无响应体。",
  },
  // ---- runs.ts（智能体运行）----
  {
    method: "get",
    path: "/api/agent/subagents",
    tag: "runs",
    auth: "user",
    successStatus: 200,
    responseSchema: agentSubagentListResponseSchema,
    summary: "列出子智能体清单",
    description:
      "返回子智能体定义注册表清单及内置派发工具（task/task_background），与真实运行同一来源。鉴权未装配时返回 503。",
  },
  {
    method: "get",
    path: "/api/agent/runs/activity",
    tag: "runs",
    auth: "user",
    successStatus: 200,
    responseSchema: agentRunActivityResponseSchema,
    summary: "查询工作区运行活动",
    description:
      "返回当前工作区近 7 天的运行次数与累计时长；解析不到工作区时返回全 0，不区分不存在与无权限。",
  },
  {
    method: "post",
    path: "/api/agent/runs",
    tag: "runs",
    auth: "optional-user",
    successStatus: 202,
    requestSchema: runCreateRequestSchema,
    responseSchema: runCreateResponseSchema,
    summary: "创建智能体运行",
    description:
      "启动一次智能体运行：补建 Code 模式会话、解析工作区默认模型、平台池额度前置拦截（余额耗尽 402）、激活执行模式与 plan 批准门，返回 202 与 runId。携带 Bearer 时鉴权；无令头允许匿名启动（本地形态）。",
  },
  {
    method: "post",
    path: "/api/agent/runs/:runId/cancel",
    tag: "runs",
    auth: "public",
    successStatus: 202,
    responseSchema: runCancelResponseSchema,
    summary: "取消运行",
    description:
      "按 runId 取消进行中的运行，找不到返回 404，成功返回 202 与取消结果。",
  },
  // ---- settings.ts（工作区设置）----
  {
    method: "get",
    path: "/api/workspace/settings",
    tag: "settings",
    auth: "user",
    successStatus: 200,
    responseSchema: workspaceSettingsResponseSchema,
    summary: "读取工作区设置",
    description: "解析当前用户 viewer 后返回其工作区的设置（含默认模型等）。",
  },
  {
    method: "put",
    path: "/api/workspace/settings",
    tag: "settings",
    auth: "user",
    successStatus: 200,
    requestSchema: workspaceSettingsUpdateRequestSchema,
    responseSchema: workspaceSettingsResponseSchema,
    summary: "更新工作区设置",
    description:
      "更新工作区设置；保存期校验默认模型是否在目录中，不存在返回 400 invalid_model 及可用清单。",
  },
  // ---- skills.ts（技能；含工作区安装态）----
  {
    method: "get",
    path: "/api/skills",
    tag: "skills",
    auth: "user",
    successStatus: 200,
    responseSchema: skillListResponseSchema,
    summary: "列出可见技能",
    description: "列出当前用户可见的技能目录（内置/社区或本人创建）。",
  },
  {
    method: "get",
    path: "/api/skills/:id",
    tag: "skills",
    auth: "user",
    successStatus: 200,
    responseSchema: skillDetailResponseSchema,
    summary: "查询技能详情",
    description:
      "按 id 返回技能详情（含正文、来源等）及关联文件列表；不可见返回 404。",
  },
  {
    method: "get",
    path: "/api/skills/:id/files",
    tag: "skills",
    auth: "user",
    successStatus: 200,
    summary: "列出技能文件",
    description:
      "按 id 返回技能附带文件的清单（路径、内容、mime 等），形如 { files }。",
  },
  {
    method: "post",
    path: "/api/skills",
    tag: "skills",
    auth: "user",
    successStatus: 201,
    requestSchema: skillCreateRequestSchema,
    responseSchema: skillDetailResponseSchema,
    summary: "创建自定义技能",
    description:
      "创建自定义技能（名称生成 slug），可附带文件；同名冲突返回 409，文件写入失败仅记日志不阻断。",
  },
  {
    method: "post",
    path: "/api/skills/import",
    tag: "skills",
    auth: "user",
    successStatus: 201,
    requestSchema: skillImportRequestSchema,
    responseSchema: skillDetailResponseSchema,
    summary: "从 URL 导入技能",
    description:
      "从外部 URL（GitHub/npm tarball/zip）下载 SKILL.md 与附属文件，落库并自动装进当前工作区。同名 409。",
  },
  {
    method: "get",
    path: "/api/skills/sandbox-packages",
    tag: "skills",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({ canvasId: z.string().describe("画布 ID（必填）") }),
    responseSchema: sandboxSkillPackageListResponseSchema,
    summary: "列出工作目录技能包",
    description:
      "按 canvasId 校验归属后扫描工作目录，列出其中的技能包候选，供「从工作目录导入」选择。画布无效返回 404。",
  },
  {
    method: "post",
    path: "/api/skills/sandbox-import",
    tag: "skills",
    auth: "user",
    successStatus: 201,
    requestSchema: sandboxSkillImportRequestSchema,
    responseSchema: skillDetailResponseSchema,
    summary: "从工作目录导入技能",
    description:
      "服务端自行读取工作目录里的技能包（不信任前端传内容），构建技能后落库并自动装进当前工作区。越界或缺 SKILL.md 返回 400，同名 409。",
  },
  {
    method: "put",
    path: "/api/skills/:id",
    tag: "skills",
    auth: "user",
    successStatus: 200,
    requestSchema: skillUpdateRequestSchema,
    responseSchema: skillDetailResponseSchema,
    summary: "更新自定义技能",
    description:
      "按 id 部分更新本人创建的技能；无可更新字段返回 400，同名冲突 409，无权限或不存在 404。",
  },
  {
    method: "delete",
    path: "/api/skills/:id",
    tag: "skills",
    auth: "user",
    successStatus: 204,
    summary: "删除自定义技能",
    description: "按 id 删除本人创建的技能；不存在或无权限返回 404，成功 204。",
  },
  {
    method: "get",
    path: "/api/workspaces/skills",
    tag: "skills",
    auth: "user",
    successStatus: 200,
    responseSchema: workspaceSkillListResponseSchema,
    summary: "列出已装工作区技能",
    description:
      "返回当前工作区已安装技能及其 enabled/installedAt 安装态信息。",
  },
  {
    method: "post",
    path: "/api/workspaces/skills",
    tag: "skills",
    auth: "user",
    successStatus: 204,
    summary: "安装技能到工作区",
    description:
      "校验技能可见后将其安装进当前工作区并启用；body.skillId 缺失返回 400，技能不可见 404，成功 204。",
  },
  {
    method: "delete",
    path: "/api/workspaces/skills/:skillId",
    tag: "skills",
    auth: "user",
    successStatus: 204,
    summary: "从工作区卸载技能",
    description: "将指定技能从当前工作区卸载；未安装返回 404，成功 204。",
  },
  {
    method: "patch",
    path: "/api/workspaces/skills/:skillId",
    tag: "skills",
    auth: "user",
    successStatus: 204,
    requestSchema: workspaceSkillToggleRequestSchema,
    summary: "启停工作区技能",
    description:
      "按 payload.enabled 切换技能在工作区的启用状态；技能不可见返回 404，成功 204。",
  },
  // ---- skills-marketplace.ts（技能市场；归 skills 域）----
  {
    method: "get",
    path: "/api/skills/marketplace/search",
    tag: "skills",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({
      q: z.string().optional().describe("搜索关键词"),
      page: z.string().optional().describe("页码"),
      limit: z.string().optional().describe("每页条数"),
    }),
    summary: "搜索技能市场",
    description: "经 npm registry 搜索 skills.sh 技能市场。市场故障返回 502。",
  },
  {
    method: "get",
    path: "/api/skills/marketplace/detail",
    tag: "skills",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({ name: z.string().describe("技能包名（必填）") }),
    summary: "查询市场包详情",
    description:
      "按包名查询 npm registry 上的技能包详情。缺 name 返回 400，包不存在 404，市场故障 502。",
  },
  {
    method: "post",
    path: "/api/skills/marketplace/install",
    tag: "skills",
    auth: "user",
    successStatus: 201,
    requestSchema: marketplaceInstallRequestSchema,
    responseSchema: skillDetailResponseSchema,
    summary: "从市场安装技能",
    description:
      "按包名从 npm registry 下载并解析技能，落库（含来源与包名元数据）后自动装进当前工作区。已安装 409，市场故障 502。",
  },
  // ---- system.ts（系统能力）----
  {
    method: "get",
    path: "/api/system/directory-picker",
    tag: "system",
    auth: "user",
    successStatus: 200,
    responseSchema: directoryPickerStatusSchema,
    summary: "查询目录选择器可用性",
    description:
      "返回原生目录对话框的可用状态与原因，供客户端决定走系统对话框还是回落浏览器目录选择器；非桌面形态如实报不可用。",
  },
  {
    method: "post",
    path: "/api/system/pick-directory",
    tag: "system",
    auth: "user",
    successStatus: 200,
    responseSchema: pickDirectoryResponseSchema,
    summary: "弹出原生目录选择",
    description:
      "调起原生目录对话框让用户选目录；非桌面形态不报错，返回 status=unavailable 及原因。无请求体。",
  },
  // ---- uploads.ts（资产上传）----
  {
    method: "post",
    path: "/api/uploads",
    tag: "uploads",
    auth: "user",
    successStatus: 201,
    multipart: {
      fileField: "file",
      fields: { projectId: "可选，归入指定项目" },
    },
    responseSchema: uploadResponseSchema,
    summary: "上传项目资产文件",
    description:
      "以 multipart 上传图片资产（仅 png/jpeg/webp/gif/svg，全局上限 10MB），先幂等引导工作区，存入 project-assets 桶。白名单外 MIME 返回 400。",
  },
  {
    method: "get",
    path: "/api/uploads/:assetId/url",
    tag: "uploads",
    auth: "user",
    successStatus: 200,
    responseSchema: assetSignedUrlResponseSchema,
    summary: "获取资产签名 URL",
    description: "按 assetId 返回资产的签名访问 URL。",
  },
  {
    method: "delete",
    path: "/api/uploads/:assetId",
    tag: "uploads",
    auth: "user",
    successStatus: 200,
    summary: "删除资产",
    description: "按 assetId 删除资产，成功返回 200 与 { ok: true }。",
  },
  // ---- usage.ts（用量）----
  {
    method: "get",
    path: "/api/usage/summary",
    tag: "usage",
    auth: "user",
    successStatus: 200,
    responseSchema: usageSummaryResponseSchema,
    summary: "查询用量汇总",
    description: "返回当前用户工作区的用量汇总（工作区隔离）。",
  },
  {
    method: "get",
    path: "/api/usage/stats",
    tag: "usage",
    auth: "user",
    successStatus: 200,
    querySchema: z.object({
      days: z
        .string()
        .optional()
        .describe("统计窗口天数，仅支持 7 或 30（默认 7）"),
    }),
    responseSchema: usageStatsResponseSchema,
    summary: "查询使用统计",
    description:
      "返回用户侧使用统计。days 仅支持 7 或 30，其他值返回 400 invalid_input。",
  },
  // ---- video-models.ts（视频模型；归 models 域）----
  {
    method: "get",
    path: "/api/video-models",
    tag: "models",
    auth: "user",
    successStatus: 200,
    summary: "列出可用视频模型",
    description:
      "从用户供应商实例目录筛选 capability=video 的模型，映射为含能力/限制/计费注解的模型清单（specifier = <instanceId>:<model>），形如 { models }。",
  },
  // ---- viewer.ts（用户视图）----
  {
    method: "get",
    path: "/api/viewer",
    tag: "viewer",
    auth: "user",
    successStatus: 200,
    responseSchema: viewerResponseSchema,
    summary: "获取当前用户视图",
    description:
      "引导（幂等）并返回当前用户的 viewer 工作区信息；附带积分信息并为 free 计划幂等领取每日积分，积分失败不阻断。",
  },
  {
    method: "patch",
    path: "/api/viewer/profile",
    tag: "viewer",
    auth: "user",
    successStatus: 200,
    requestSchema: profileUpdateRequestSchema,
    responseSchema: profileUpdateResponseSchema,
    summary: "更新用户资料",
    description:
      "更新当前用户的显示名并返回更新后的资料。校验失败返回 400 带 issues。",
  },
];
